picolibc/picolibc

newlib/libm/mathfp/meson.build

Hi again!
This one's a really simple buildfix. `math` has `libm/common` on the include path, while `mathfp` doesn't! This patch fixes that and lets mathfp compile.
Thanks,
-Ash

Buildfix for hardware floating-point machines

---

newlib/libc/machine/powerpc/meson.build

Heya!
This adds a meson buildscript for the PowerPC machine folder. I had to leave off the vec_ files since they directly use reentrant syscalls, __malloc_lock, and other things like that. Those files are SIMD extensions in any case, and can always be patched and enabled later. Otherwise, cross-compiling to PowerPC seems to work great!
Thanks again,
-Ash

Add build files for PowerPC platforms

---

newlib/libc/include/sys/_types.h
newlib/libc/include/sys/reent.h
newlib/libc/stdio/meson.build

Heya!
I recently found out about picolibc, and dang, it's really nice to have a version of newlib that has a more usable build system - I've lost more time than I'd like to admit trying to add source files to newlib upstream!
In any case, I'm trying this in a use case where file I/O is needed, therefore newlib's usual stdio. While I haven't tried it in practice yet, there was a typedef needed and an extra source file for it to compile - which is what you'll find in this patch.
Thanks for the awesome work! I've got a few more PRs incoming, hopefully they're useful.
-Ash

Buildfix for using newlib's stdio

---

README.md
doc/embedsource.md
meson.build

For projects where deterministic builds, reproduceability and traceability is important, it is possible to embed the entire picolibc library as a meson subproject into the source directory of the master project. The benefit is that git submodules and meson subprojects work nicely together, and it is possible to lock down the libc version together with the source tree.
Refer to doc/embedsource.md how to embed picolibc into your source tree

Export meson dependency for embedding picolibc into source tree

---

cross-xtensa-lx106-elf.txt
newlib/libc/include/machine/ieeefp.h
newlib/libc/machine/xtensa/machine/core-isa.h
newlib/libc/machine/xtensa/memcpy.S
newlib/libc/machine/xtensa/memset.S
newlib/libc/machine/xtensa/meson.build
newlib/libc/machine/xtensa/setjmp.S
newlib/libc/machine/xtensa/strcmp.S
newlib/libc/machine/xtensa/strcpy.S
newlib/libc/machine/xtensa/strlen.S
newlib/libc/machine/xtensa/strncpy.S
newlib/libc/machine/xtensa/xtensa-asm.h
newlib/libc/meson.build
newlib/libm/machine/xtensa/feclearexcept.c
newlib/libm/machine/xtensa/fegetenv.c
newlib/libm/machine/xtensa/fegetexcept.c
newlib/libm/machine/xtensa/fegetexceptflag.c
newlib/libm/machine/xtensa/fegetround.c
newlib/libm/machine/xtensa/feholdexcept.c
newlib/libm/machine/xtensa/feraiseexcept.c
newlib/libm/machine/xtensa/fetestexcept.c
newlib/libm/machine/xtensa/feupdateenv.c
newlib/libm/machine/xtensa/meson.build

This takes the work by Max Filippov for newlib, which is in turn based on Tensilica's work, and tries to import the minimal amount needed to get picolibc working. Tested on a ESP8266 with the 2.2.1 + 3.0.1 Espressif NONOS SDKs + GCC 9.2.1 from Debian.
The only issue I haven't worked out how to cleanly handle is that the standard SDK treats uint32_t as int, but stdint.h will default to it being long for the lx106/ESP8266 - the vendor supplied file has a hack to force uint32_t to int for TENSILICA but that doesn't seem clean.
I have a patch to build a picolibc that's useful for the Debian gcc-xtensa-lx106 packages as well, which I'll file separately.

Add initial support for ESP8266 (xtensa-lx106-elf)

---

debian/control
debian/picolibc-xtensa-lx106-elf.install
debian/picolibc-xtensa-lx106-elf.lintian-overrides
debian/picolibc-xtensa-lx106-elf.triggers
debian/rules

Build the lx106 library. Unlike the existing arm/riscv variants we install this directly into the configured gcc paths; there is no alternative libc in Debian for this platform so this should be the default.
(obviously needs lx106 support merged in, but I've confirmed doing that from master and throwing the tree at sbuild works as expected.)

debian: Enable package for xtensa-lx106 (ESP8266)

---

newlib/libm/common/math_config.h

Clang 9 is complaining about this and the code appears to be wrong.
```
In file included from /home/ayke/src/github.com/tinygo-org/tinygo/lib/picolibc/newlib/libm/common/s_expm1.c:145:
/home/ayke/src/github.com/tinygo-org/tinygo/lib/picolibc/newlib/libm/common/math_config.h:222:24: error: pragma diagnostic pop could not pop, no matching push [-Werror,-Wunknown-pragmas]
#pragma GCC diagnostic pop
^
1 error generated.
```
Note that I'm using a custom build system (to avoid external dependencies, among other reasons) so perhaps there is something different in my setup that causes this error to appear.
---
Sidenote: thanks a lot for your work on picolibc! It's being used now as a C library in TinyGo for most bare metal targets: https://github.com/tinygo-org/tinygo/pull/871

Fix unbalanced diagnostics pragma

---

newlib/libc/string/strncpy.c

This PR just correct the typo in DESCRIPTION of strncpy function.
Old: copies not more than <[length]> characters from **the the** string
New: copies not more than <[length]> characters from **the** string

Correct the typo in the DESCRIPTION

---

newlib/libm/test/math.c

clang complains about this
Also, duplicate import <math.h> and unused variable "verbose" removed

Tests fix: duplicate declarations of inacc, reduce, redo

---

newlib/libc/include/assert.h
newlib/libc/stdlib/assert.c

Is this acceptable?
I just figured out why my project shows assertion erros with garbage while moved from Linux to bare metal.
Is there any standard for `__assert` args?

Changes __assert args order (as in glibc)

---

newlib/libc/tinystdio/dtoa_ryu.c
newlib/libc/tinystdio/ftoa_ryu.c
newlib/libc/tinystdio/ryu/common.h

As suggested, I removed the macros `min` and `max`, and added a (shared) `static inline` function instead.

Replace min/max macro with an inline function

---

meson.build
newlib/libc/ctype/categories.c
newlib/libc/ctype/towctrans_l.c

[as discussed here](https://github.com/archi/picolibc/commit/95e36dcb433487100c60dbede471bc8d0a2feae4#diff-dbb6f244761a8bcf0d19ad05020e6be0): Check if compiler can supports bitfields inside packed structs.
This commit has been cherry picked from my compcert branch.

Check if compiler supports bitfields in packed structs

---

scripts/do-configure
scripts/do-freedom-tools-configure
scripts/do-freedom-tools-package

Adds a script which automates the packaging of picolibc for SiFive Freedom Tools.
The script takes a single argument, the version of picolibc. The calendar version of Freedom Tools is inferred from the compiler with `--version`.

Create packaging script for Freedom Tools

---

meson.build
newlib/libc/stdlib/mallocr.c
newlib/libc/stdlib/mul_overflow.h
newlib/libc/stdlib/nano-mallocr.c
newlib/libc/stdlib/reallocarray.c

After being tricked by git, this is a second attempt at PR #57 - now with cleaner commit :)
from commit:
Check for presence of __builtin_mul_overflow
ONLY if it's not there, use a software implementation.
That software implementation assumes size_t to be compatible with
CompCert (which does support neither statement expressions (=> no
macro magic) and no _Generic).
In two of the three locations this is no problem at all, since they are
hardcoded to operate on size_t. But the third location only defaults to
size_t - but that can be overwritten by some define.
However, I don't think that's a real problem: Previously compilers
without __builtin_mul_overflow were not supported at all, now they're
supported as long as the user sticks to a default setting.
An appropriate `#error` has been …

Check for presence of __builtin_mul_overflow

---

newlib/libc/include/machine/_default_types.h

Since the check from PR #77 is only really used in one place, I simplified that change.

check for __INT_MAX__ & friends, simpler variant

---

meson.build
newlib/libc/include/sys/cdefs.h
newlib/libc/tinystdio/vfprintf.c
newlib/libm/test/meson.build
newlib/testsuite/newlib.iconv/meson.build
scripts/duplicate-names

This PR contains various small fixes to make the whole library including tests buildable on Macos.
The `__weak_reference` is a bit of a kludge because it seems to be necessary to mark the original symbol as weak when creating a weak reference for the exported symbol to actually become weak. Building the stack-smash test fails if the `__stack_check_fail` symbol is not correctly marked as weak so it can be used as a test for this if anybody wants to experiment further, but this is the best I have managed to come up with for now.
The `printff_scanff` and `printff-tests` tests fail because of not being correctly linked after I had to remove the `-spec` flags when building on Clang.
The `fenv` test seems very broken on Mac, a whole bunch of test cases get zero or ~ulp.
`math_errhandling` tests …

Mac build fixes

---

newlib/libc/stdio/sys/meson.build

This replicates the logic of the other sys/ header file installation. Proposed fix for issue #88 

libc/stdio: Allow machine dependent files to override sys/stdio.h

---

newlib/libc/machine/arm/aeabi_memcpy.c
newlib/libc/machine/arm/aeabi_memmove.c
newlib/libc/machine/arm/aeabi_memset.c

Otherwise r0 register will contain unexpected value obtained from asm code.

memcpy declaration fix

---

newlib/libc/include/math.h

And a small one: As the title says, CompCert has these builtins, so they should be used. This also removes bogus warnings when the e.g. the INFINITY constant is used.
Since `math.h` is an installed header, I check for the magic define instead of handling this in the build system.

CompCert: Use more builtins in math.h

---

doc/os.md
doc/using.md
hello-world/Makefile
hello-world/hello-world.c
meson.build
picocrt/crt0.h
picocrt/machine/riscv/crt0.S
picocrt/meson.build
picolibc.specs.in
test/constructor-skip.c
test/constructor.c
test/hosted-exit.c
test/meson.build

This builds on PR #109 by making the selection of crt0 separate from the oslib version.

Split out crt0 selection from oslib selection

---

meson.build
test/meson.build

Once again, an attribute that CompCert does not support. From my commit log:
These are GNU extension, and if the compiler doesn't have them, there is
no point testing for correct behavior.
This only affects the test. Other locations use that attribute, too
(at least the ssp). So maybe it would make sense to use make wider use
of the new test.
Apply the better test (with '-Werror' -- if available) to the other
attribute test as well.

Test for 'constructor'/'destructor' attributes

---

meson.build

CompCert has no specs files, but it's easier to use picolibc via the
specs file file. (The alternative is to extend the build scripts to
produce the correct compcert.ini [the ccomp equivalent of specs] and
keep that in sync with what the normal specs file does - suboptimal
to maintain).
Hence, we instruct the ccomp to pass the --spec to the linker.

Pass --specs parameter for CompCert using -WUl

---

newlib/libc/tinystdio/fread.c

The without the new condition, `fread(foo, 0, x, bar);` would return
`x`: The outer loop iterates that many times (doing nothing).
However both C11 (7.21.8.1) and C99 (7.19.8.1) expect fread to return 0.
The standard says:
> The fread function returns the number of elements successfully read, which may be
> less than nmemb if a read error or end-of-file is encountered. If size or nmemb is zero,
> fread returns zero and the contents of the array and the state of the stream remain
> unchanged

tinystdio: Fix handling of fread with size=0

---

newlib/libc/include/sys/cdefs.h

Just a minor fix: Since CompCert properly defines `__func__`, it should not be set to `NULL`. Since this is `cdefs.h`, the check is also needed during compile time of the actual program, not just the lib.
No test here, since this really just depends on the compiler ;-)
There is a comment how there should be a better check here, but I don't know enough about other compilers/preprocessors to just enable that. So I sticked to keeping it simple.
Regarding the other PRs:
> I've merged in a fix and your tests; thanks so much for finding this (and creating test cases!)
You're welcome! And thanks back to you as well: For doing picolibc and making contribution so straight-forward :)

CompCert also properly defines __func__

---

test/meson.build
test/time-tests.c

This is the kind of manual tests I would add for timegm() and co.
The GNU C Library tests the boundaries of the year 2038 problem, see file time/tst-timegm.c . In the next patch iteration I would add such tests too.
I am not sure yet what coding style is desired, whether // comments are OK, hopefully spaces instead of tabs, etc. But I don't really want to invest too much time in source code styling. Do you have a tool and its configuration to automatically reformat the source code for Picolibc?

Add more tests against timegm()

---

meson.build

As the title says: This patch checks if the compiler supports '-fno-stack-protector' before adding it to the list of options.
The `-U`ndefine should be safe for most compilers, so I did not touch it.

check if the compiler supports '-fno-stack-protector'

---

test/malloc_stress.c

Signed-off-by: R. Diez <rdiezmail-newlib@yahoo.de>

Remove definition of abort() from malloc_stress.c

---

newlib/libc/stdlib/nano-mallocr.c
test/malloc_stress.c

On 32-bit targets, nano malloc aligns the first block from the heap so that the returned allocation is 8-byte aligned even though the header is 4 bytes long. This "wastes" 4 bytes at the start of the heap, which aren't accounted for in the computation returned from mallinfo, making the uordblks value off by 4 bytes. Fix this by marking the start of the heap at the start of the first aligned block. This has the additional benefit of saving a call to sbrk(0).

libc: Set heap start for nano-malloc at first aligned block

---

.github/workflows/macos.yml
.github/workflows/minsize.yml
.github/workflows/release.yml

Instead of running on any push/PR, only run on push/PR to main.

.github: Reduce scope of actions

---

newlib/empty.c
newlib/libc/meson.build
newlib/libm/meson.build
newlib/libm/test/meson.build
newlib/meson.build

Instead of creating a separate libm containing math functions, merge  those into libc. This simplifies application development and enables use of math functions in the core C library.
A stub libm is still created and installed that contains no contents.

Merge core C library with math library

---

newlib/libc/tinystdio/meson.build

atold_engine.c is currently only used when building strtold.c as
vfscanf doesn't have long double support at this point. Compiling this
file generates numerous warnings on hosts like arm where long double
is the same type as double.

tinystdio: Avoid building atold_engine.c unless needed

---

doc/printf.md
newlib/libc/stdio/stdio.h
newlib/libc/stdio/vfprintf.c
newlib/libc/stdio/vfwprintf.c
newlib/libc/tinystdio/scanf_private.h
newlib/libc/tinystdio/stdio_private.h
newlib/libc/tinystdio/vfprintf.c
newlib/libc/tinystdio/vfscanf.c
test/printf_scanf.c

printf supports long long, but that was missing from scanf.

Add long long support to tinystdio scanf

---

newlib/testsuite/newlib.iconv/meson.build
newlib/testsuite/newlib.locale/meson.build
newlib/testsuite/newlib.search/meson.build
newlib/testsuite/newlib.stdio/meson.build
newlib/testsuite/newlib.stdlib/meson.build
newlib/testsuite/newlib.string/meson.build
newlib/testsuite/newlib.wctype/meson.build
test/meson.build
test/semihost/meson.build

lib_m is now empty, so there's no need to include that when linking
tests.

test: Don't use lib_m when building tests

---

.editorconfig
doc/printf.md
hello-world/Makefile
meson.build
newlib/libc/tinystdio/ultoa_invert.c
newlib/libc/tinystdio/vfprintf.c
test/meson.build
test/testcases.c

I was cleaning up the tinystdio printf code to make it more readable, adding comments and untangling the conditionals when I found a couple of bugs and some opportunities to shrink the code.
bugs:
*  'hh' length modifier not supported in integer-only printf.
*  %q for q some non-supported format char would consume an integer argument from the input

Fix tinystdio printf bugs, shrink code

---

newlib/libc/tinystdio/stdio.h

C++ requires that designated initializers, like the ones used in
the `FDEV_SETUP_STREAM` macro, must be in the order in which they appear
in the data members of the `__file` struct. See:
https://en.cppreference.com/w/cpp/language/aggregate_initialization
Move the `.flags` initialization to the top of the initializer list
for the macro `FDEV_SETUP_STREAM`.
Perform the same with `fdev_setup_stream` to keep them consistent.

Fix __file flag initialization for C++ apps

---

meson.build

This will cause any uses of variable length arrays to generate a
compile-time error.

Add -Werror=vla to build

---

doc/build.md
doc/os.md
dummyhost/iob.c
newlib/libc/include/sys/cdefs.h
newlib/libc/stdlib/pico-onexit.c
newlib/libc/tinystdio/posixiob.c
newlib/libc/tinystdio/stdio.h
newlib/testsuite/stdio-bits.c
semihost/iob.c
semihost/machine/i386/e9_io.c

This swaps the __iob array for global variables, which conform to the
POSIX spec more closely, avoid using array indexing which might
generate longer code on some platforms and allow sharing all three in
a single location in ROM with symbol aliasing.
This changes the tinystdio API/ABI in an incompatible fashion.

tinystdio: Use simple globals for stdin/stdout/stderr

---

newlib/libc/stdlib/pico-onexit.c

C99 does not permit empty initializer lists. See "6.7.8 Initialization".
I'd expect most compilers to happily do the "right thing", but CompCert
is a little bit more strict here.
---
Let's see if I'm right once the CI on GitHub is finished :)

Initializer lists shall not be empty

---

.github/workflows/macos.yml
.github/workflows/minsize.yml
.github/workflows/release.yml
doc/printf.md
meson.build
meson_options.txt
newlib/libc/tinystdio/meson.build
newlib/libc/tinystdio/scanf_private.h
newlib/libc/tinystdio/vfiprintf.c
newlib/libc/tinystdio/vfiscanf.c
newlib/libc/tinystdio/vfprintf.c
newlib/libc/tinystdio/vfprintff.c
newlib/libc/tinystdio/vfscanf.c
newlib/libc/tinystdio/vfscanff.c
newlib/libm/test/meson.build
test/meson.build

This option selects which printf/scanf variant is the default for the
library
-Dformat-default=double		vfprintf/vfscanf support double (and float for scanf)
-Dformat-default=float		vfprintf/vfscanf support floats, not double
-Dformat-default=integer	vfprintf/vfscanf do not support floating point
Applications wanting other floating point support may select that at build time
using:
-DPICOLIBC_DOUBLE_PRINTF_SCANF	always choose version with double support
-DPICOLIBC_FLOAT_PRINTF_SCANF	always choose version with float support
-DPICOLIBC_INTEGER_PRINTF_SCANF	always choose version without float/double support

tinystdio: Add -Dformat-default configuration option

---

newlib/libc/tinystdio/meson.build
newlib/libc/tinystdio/rewind.c

This function was missing, although was defined in stdio.h.

tinystdio: Add rewind(3)

---

meson.build

Mac OS X expr doesn't have the substr operator, so use regex with ':'
instead.
Closes #174

Use expr ':' instead of 'substr' operator

---

newlib/libc/string/strrchr.c
test/meson.build
test/test-strchr.c

Reported by prodisDown:
In picolibc/newlib/libc/string/strrchr.c
if (i) { while ((s=strchr(s, i))) { last = s; s++; } } else { last = strchr(s, i); }
Value (for example 0xFFFFFF00) in if (i) can pass test and
then be typecasted to char inside strchr(). Then s++ and then
buffer overrun.
It can be fixed by preventive typecast i = (int) (char) i; or
typecasting inside expression if ((char) i).
Fixed by casting to char.
Fixes #184 

string: Fix buffer overrun in picolibc/newlib/libc/string/strrchr.c. Fixes #184

---

meson.build
newlib/libm/test/meson.build
newlib/testsuite/newlib.iconv/meson.build
newlib/testsuite/newlib.locale/meson.build
newlib/testsuite/newlib.search/meson.build
newlib/testsuite/newlib.stdio/meson.build
newlib/testsuite/newlib.stdlib/meson.build
newlib/testsuite/newlib.string/meson.build
newlib/testsuite/newlib.wctype/meson.build
scripts/monitor-e9
semihost/machine/i386/meson.build
test/meson.build
test/semihost/meson.build

When I `meson test -C builddir-x86_64` after `meson configure`, all tests failed with timeouts.  It was same for i386, too.  But other arches just worked.  Strangely, `.github/do-test` works for both x86s.  I didn't know what was going on but figured out that there were two issues
1. `monitor-e9` was busy looping waiting for qemu to spit `\xe9` when `qemu` was already dead because of `bios.bin` not found.
2. For i386 and x86_64, we need `bios.bin` to run the tests but no tests depends on it.  This make `qemu` to exit immediately.
This PR has two commits addressing the issues.

Fix test dependency

---

scripts/cross-clang-riscv64-unknown-elf.txt
scripts/cross-clang-rv32imafdc-unknown-elf.txt
scripts/cross-i686-linux-gnu.txt
scripts/cross-riscv64-unknown-elf.txt
scripts/cross-riscv64-zephyr-elf.txt
scripts/cross-rv32imac.txt

Kill most of warnings from meson.
The remaining one is:
```
DEPRECATION: c_args in the [properties] section of the machine file is deprecated, use the [built-in options] section.
```
But, this one can't be fixed until we bump meson version to 0.56.
https://mesonbuild.com/Machine-files.html#meson-builtin-options
Distribution version having Meson 0.56 or later are:
- Ubuntu 21.04 Hirsute or later
- Debian 11 Bullseye or later
- Fedora 33 or later

Kill warnings

---

meson.build

This PR does two things:
- Replace the option check with `get_supported_arguments()`
- Replace `-Wall` and `-Wextra` with `warning_level()`

Refactor compiler warnings

---

.github/workflows/fortity-source-arm.yml
.github/workflows/fortity-source-riscv.yml
.github/workflows/fortity-source.yml
.github/workflows/minsize-arm.yml
.github/workflows/minsize-riscv.yml
.github/workflows/release-arm.yml
.github/workflows/release-riscv.yml
.github/workflows/release.yml

Reduce the number of jobs in each build well below the 256 limit to
keep the CI system happy.

.github: Split out arm and risc-v CI builds

---

meson.build
newlib/libc/posix/engine.c
newlib/libc/search/qsort.c
scripts/cross-clang-riscv64-unknown-elf.txt
scripts/cross-clang-rv32imafdc-unknown-elf.txt
test/libc-testsuite/qsort.c

qsort's pointer alignment test was using pointer subtraction to convert a pointer to an integer. Replace this with a simple cast to uintptr_t instead, which (while probably still undefined behavior), at least isn't called out explicitly in the ISO spec, and doesn't trigger a warning from clang?

Make clang happy with qsort pointer alignment test

---

meson.build

Newlib is defining the `__NEWLIB__` and `__NEWLIB_MINOR__` macros to export
the library version.
The current meson build in picolibc is exporting `_NEWLIB__` and
`_NEWLIB_MINOR__` (with only one initial underscore).
Align the picolibc behavior on the newlib one.
This fixes the build of LLVM libcxx which is using those macros to pick
the right headers in the following file:
https://github.com/llvm/llvm-project/blob/main/libcxx/include/__support/newlib/xlocale.h

Fix newlib version macros

---

meson.build
test/libc-testsuite/fnmatch.c
test/libc-testsuite/sscanf.c
test/math_errhandling_tests.c
test/testcases.c

When I initially created the meson build files, I mistakenly used only
a single leading underscore in all of the version macros. This adds
double leading underscore names, leaving the single underscore names
for anyone using them.

Add double-underscore PICOLIBC version macros

---

meson.build

There are two typo for the keyword 'description' for config data set() in meson.build.
Meson 0.61 doesn't warn about this but a post v0.61 with the commit [mesonbuild/meson/commit/574525673f6](https://github.com/mesonbuild/meson/commit/574525673f6) will error out with:
```
meson.build:737:10: ERROR: configuration_data.set got unknown keyword arguments "descrption"
```
This is reported by @tcal-x.
Closes #244.
Signed-off-by: Yasushi SHOJI <yashi@spacecubics.com>

meson.build: Fix description keyword in configuration set()

---

meson.build
meson_options.txt
newlib/libc/picolib/inittls.c
newlib/libm/common/pow.c
picocrt/crt0.h
picolibc.ld.in
scripts/cross-m68k-linux-gnu.txt
scripts/do-m68k-configure
scripts/test-m68k.ld
semihost/fake/fake_exit.c
semihost/fake/fake_io.c
semihost/fake/fake_kill.c
semihost/fake/fake_stub.c
semihost/fake/meson.build
semihost/meson.build

This series adds a -Dcrt-runtime-size=true option which tells picolibc to compute the size of the bss, data, tbss and tdata segments at runtime by subtracting addresses rather than having the linker perform that subtraction at link time. This can be necessary if the toolchain doesn't deal with relocating the size values as 'addresses'.
Closes #246

Compute memory region sizes at runtime

---

dummyhost/meson.build
meson.build
meson_options.txt
newlib/libc/include/machine/meson.build
newlib/libc/include/meson.build
newlib/libc/include/ssp/meson.build
newlib/libc/include/sys/meson.build
newlib/libc/machine/aarch64/sys/meson.build
newlib/libc/machine/arm/machine/meson.build
newlib/libc/machine/arm/sys/meson.build
newlib/libc/machine/i386/machine/meson.build
newlib/libc/machine/riscv/machine/meson.build
newlib/libc/machine/riscv/sys/meson.build
newlib/libc/machine/shared_x86/sys/meson.build
newlib/libc/machine/xtensa/machine/meson.build
newlib/libc/machine/xtensa/sys/meson.build
newlib/libc/stdio/meson.build
newlib/libc/stdio/sys/meson.build
newlib/libc/tinystdio/meson.build
newlib/meson.build
picocrt/meson.build
picolibc.specs.in
semihost/fake/meson.build
semihost/machine/i386/meson.build
semihost/meson.build

These two options let picolibc be built with multiple configuration options and
installed in the same target directory. At application compile time, the build type
can be selected via the GCC --picolibc-buildtype option which selects which target
path to use for headers and binaries.
This will allow pre-built binaries to include both minsize and release builds so that developers can choose which version to use instead of having to rebuild picolibc for each application.
Closes #258

Add '-Dbuild-type-subdir' to meson and '--picolibc-buildtype' to gcc

---

README.md
doc/build.md
doc/locking.md
meson.build

build.md had lagged behind changes to meson_options.txt and the section on locking needed expanding to define the API used by the library.
Closes #266

Update build.md, syncing with meson_options, add locking.md

---

meson.build
scripts/cross-aarch64-linux-gnu.txt
scripts/cross-aarch64-zephyr-elf.txt
scripts/cross-arm-none-eabi.txt
scripts/cross-arm-zephyr-eabi.txt
scripts/cross-clang-riscv64-unknown-elf.txt
scripts/cross-clang-rv32imafdc-unknown-elf.txt
scripts/cross-clang-thumbv7e+fp-none-eabi.txt
scripts/cross-clang-thumbv7m-none-eabi.txt
scripts/cross-cortex-a9-none-eabi.txt
scripts/cross-i686-linux-gnu.txt
scripts/cross-riscv64-unknown-elf.txt
scripts/cross-riscv64-zephyr-elf.txt
scripts/cross-rv32imac.txt
scripts/cross-x86_64-linux-gnu.txt

Meson version 0.53.2 (at least) doesn't check for the
skip_sanity_check value before attempting to run test fragments during
configuration. That means the exe_wrapper value needs to handle being
run at that point. To support this, the exe_wrapper becomes a script
which checks for a environment variable (PICOLIBC_TEST) and exits
indicating success if that is not present.
Closes #270 

scripts: Support meson 0.53.2 by adjust exe_wrappers

---

newlib/libc/tinystdio/atof_ryu.c
newlib/libc/tinystdio/ftoa_engine.c
newlib/libc/tinystdio/ftoa_ryu.c

This fixes a few issues in tinystdio where the code assumed the int type (which is the default for integer literals) is at least 32 bits.
It might not fix all issues, only the ones I hit when trying to get picolibc to work on AVR.

tinystdio: support 16-bit int type

---

newlib/libc/machine/m68k/memcpy.S

It's a stretch to call misaligned writes "OK" on 68010. It supports
them in _software_, if and only if the operating system provides an
address error handler that knows how to emulate the
access. Newlib/picolibc does not provide this, and even if it did,
vectoring to a software emulation routine for every single
word/longword access is WAY slower than just copying byte for
byte. The 68010 should probably be removed from this.
Closes #286 
Reported by: Alexis Lockwood

m68k: Don't use unaligned access on m68010 memcpy

---

newlib/libc/tinystdio/vfprintf.c
newlib/libc/tinystdio/vfscanf.c
test/printf_scanf.c

%p needs to adjust parameter size on targets where sizeof(void *) > sizeof(int).

Handle %p on ILP64 targets

---

meson.build
meson_options.txt
newlib/libc/stdio/fmemopen.c
newlib/libc/stdio/fopencookie.c
newlib/libc/stdio/funopen.c
newlib/libc/stdio/open_memstream.c
newlib/libc/stdio/swprintf.c
newlib/libc/stdio/vswprintf.c
newlib/testsuite/newlib.stdio/swprintf.c

EL/IX is a RedHat specification for embedded library API levels, which
newlib uses. When that value was migrated to picolibc, the default
value was set to 2, while newlib uses '4'. And some code depends on
_ELIX_LEVEL being set to that value.

Set default EL/IX to '4'. Set _ELIX_LEVEL

---

CMakeLists.txt

The picolibc.specs file lives in the build directory, not the source directory.
The picolibc.h file wasn't getting copied to the install include directory.

Fix issues with out of source build CMake install.

---

doc/build.md

Hi,
first time user of picolib - so I read the build documentation extra carefully, and came up with these two fixes to the `build.md`:
- do-*-configure scripts seem to have moved.
- Add note on selecting installation directory.
P.s. After using picolib for ca. 5 minutes, I can only say it looks awesome! The execution time of my application (a neural network, so heavy on the libm) dropped from 200ms with newlib to 33ms with picolib - only change needed was to change the `--specs` option to gcc. And even the ROM usage shrank with a few percent. Thank you for this project! :)

Fix and improve build.md.

---

newlib/libc/tinystdio/vfprintf.c

A short series that restructures the integer format handling code a bit to shrink it while (I hope) making it a bit clearer.
This reduced the text size on all 32-bit arm and all risc-v targets, from 16 to 104 bytes.
Here's complete data:
arm:
```
old 18752 new 18720 diff -32 test/printfi-tests
old 18528 new 18496 diff -32 test/printfi-tests_arm_v5te_hard
old 18528 new 18496 diff -32 test/printfi-tests_arm_v5te_softfp
old 13812 new 13796 diff -16 test/printfi-tests_thumb_nofp
old 13548 new 13532 diff -16 test/printfi-tests_thumb_v6_m_nofp
old 13972 new 13892 diff -80 test/printfi-tests_thumb_v7_a_fp_hard
old 13972 new 13892 diff -80 test/printfi-tests_thumb_v7_a_fp_softfp
old 13972 new 13908 diff -64 test/printfi-tests_thumb_v7_a_nofp
old 13972 new 13908 diff -64 …
```

Shrink vfprintf integer handling code

---

newlib/libc/machine/i386/memchr.S
newlib/libc/machine/i386/memcmp.S
newlib/libc/machine/i386/memcpy.S
newlib/libc/machine/i386/memmove.S
newlib/libc/machine/i386/memset.S
newlib/libc/machine/i386/setjmp.S
newlib/libc/machine/i386/strchr.S
newlib/libc/machine/i386/strlen.S
newlib/libc/machine/x86_64/memcpy.S
newlib/libc/machine/x86_64/memset.S
newlib/libc/machine/x86_64/setjmp.S
picocrt/machine/i386/crt0.S
picocrt/machine/x86_64/crt0.S

Current GCC compiler bits for Linux complain when assembly code
doesn't explicitly note that it doesn't require an executable
stack. As both x86 test builds use the Linux toolchain, they've
started complaining. Add these notes, even though it really doesn't
matter to us.

x86: Note that asm code doesn't require executable stack

---

newlib/libc/tinystdio/scanf_private.h
newlib/libc/tinystdio/vfscanf.c

Instead of embedding the base in the flags parameter, pass the
value explicitly and then use that in simple computation instead of
using the 'mulacc' helper function.
This saves space on every ARM target.

tinystdio: Add explicit 'base' when parsing ints in scanf

---

cmake/picolibc.cmake
newlib/libc/stdlib/CMakeLists.txt

These files need to be compiled without the compiler "knowing" how
malloc and free work as that messes up the malloc/free
implementation. Copy the parameters used for meson into the cmake
build system.

cmake: Use -fno-builtin-malloc -fno-builtin-free for malloc sources

---

picocrt/machine/riscv/meson.build
picocrt/meson.build

For some reason, current binutils bits now require appending _zicsr to
the -march flag to enable CSR access instructions. Fix this by hacking
up the -march flag provided by the build system to append _zicsr while
building picocrt but not other parts of the library.

picocrt: Risc-V binutils at 2.38 requires _zicsr to get CSR ISA

---

meson.build
picocrt/machine/riscv/meson.build
picocrt/meson.build

It seems that GCC 12 gets confused by newlib/libm/common/copysignl.c
and thinks it's a recursive function. Disabling the builtin
'copysignl' avoids this; as copysignl isn't actually used anywhere
else, this doesn't affect other code.
Ideally, perhaps every wrapper around a builtin function should be
compiled with just that builtin disabled?

Add -fno-builtin-copysignl to default compiler args

---

newlib/libc/include/fenv.h

On aarch64 (and others), sys/fenv.h includes definitions of inline
versions of the various fenv functions. If those aren't enclosed in
the extern "C" block, then they appear as native C++ functions.
Make sure that doesn't happen by including sys/fenv.h inside the
extern "C" block instead of outside.

libc/include: Wrap <sys/fenv.h> inside the extern "C" block for C++

---

scripts/cross-clang-old-riscv64-unknown-elf.txt
scripts/cross-clang-old-rv32imafdc-unknown-elf.txt
scripts/cross-clang-riscv64-unknown-elf.txt
scripts/cross-old-clang-riscv64-unknown-elf.txt
scripts/cross-rv32imac_zicsr.txt
scripts/do-clang-riscv-configure
scripts/do-clang-rv32imafdc-configure
scripts/do-rv32imac-configure

Debian now includes GCC 12.1.0 for risc-v, which means that -march
must include _zicsr to build picocrt, but must not include _zicsr when
linking as that won't find the libraries. In addition, the clang build
needs an updated linker path to find libgcc.

risc-v: Update cross scripts for new Debian risc-v toolchain

---

newlib/libm/math/k_rem_pio2.c
newlib/libm/math/kf_rem_pio2.c

These functions set the 'fq' values in a loop which GCC can't figure
out are actually set, so it emits a warning. Instead of adding code to
initialize these variables (which are arrays of 20 elements), silence
the warning.

math: Ignore maybe uninitialized warning in both rem_pio2 funcs

---

.github/workflows/linux.yml
.github/workflows/make-workflow
.github/workflows/targets-misc
.github/workflows/targets-sparc64
meson.build
meson_options.txt
semihost/getentropy.c
semihost/meson.build

Add an option to remove include and library path definitions from picolibc.specs for use when
picolibc is the system C library.

System libc option

---

newlib/libc/stdio/fputws.c

Encounter this when use `newlib-fvwrite-in-streamio` option.

Fix references to _r function

---

newlib/libc/stdlib/__atexit.c

I think something must have gone wrong with the merge in 3b8c9b74e6d1a6e9bc5a8fda5853a78a09a9d174, resulting in the loss of an `#endif` in stdlib/__atexit.c?

newlib/stdlib: Fix unbalanced preprocessor #if

---

picocrt/machine/arm/crt0.c

In the A32 instruction set MOV (immediate) and MOVS (immediate) are equivalent. However in the T32 instruction set MOV must be used inside an IT block and MOVS must be used outside an IT block. Since this code is not in IT blocks MOVS must be used for the code to compile as T32.

Fix MOV that's invalid as a T32 encoding

---

.github/workflows/linux.yml
.github/workflows/targets-arm
picocrt/machine/arm/crt0.c
scripts/cross-clang-thumbv6m-none-eabi.txt
scripts/do-clang-thumbv6m-configure
scripts/run-thumbv6m

PR #340 fixes a bug for thumbv6m targets in picocrt; this PR adds tests to validate the fix

Fix picocrt build with clang for thumbv6m

---

.github/Dockerfile
.github/packages.txt
newlib/libc/machine/x86/meson.build
newlib/libm/machine/x86/meson.build
semihost/machine/x86/meson.build

Only build one copy of bios.bin, using -nostdlib to avoid looking for libc.
Make sure all 32-bit targets,even 32/soft-float get the i386 specific bits.

x86: More 64/32 multilib build fixes

---

CMakeLists.txt
newlib/libc/machine/aarch64/CMakeLists.txt
newlib/libc/machine/aarch64/machine/CMakeLists.txt
newlib/libc/machine/aarch64/sys/CMakeLists.txt
newlib/libc/machine/arc/CMakeLists.txt
newlib/libc/machine/mips/CMakeLists.txt
newlib/libc/machine/mips/machine/CMakeLists.txt
newlib/libc/machine/mips/sys/CMakeLists.txt
newlib/libc/machine/nios2/CMakeLists.txt
newlib/libc/machine/sparc/CMakeLists.txt
newlib/libc/machine/sparc/machine/CMakeLists.txt
newlib/libc/machine/sparc/sys/CMakeLists.txt
newlib/libc/machine/x86/machine/CMakeLists.txt
newlib/libc/machine/xtensa/CMakeLists.txt
newlib/libc/machine/xtensa/machine/CMakeLists.txt
newlib/libc/machine/xtensa/machine/core-isa.h
newlib/libc/machine/xtensa/meson.build
newlib/libc/machine/xtensa/sys/CMakeLists.txt
newlib/libm/machine/aarch64/CMakeLists.txt
newlib/libm/machine/mips/CMakeLists.txt
newlib/libm/machine/sparc/CMakeLists.txt
newlib/libm/machine/xtensa/CMakeLists.txt
picolibc.h.in

Three cmake fixes to bring it up to parity with meson and an xtensa which uses the toolchain core-isa.h file if available.

Fixes found with Zephyr testing

---

meson.build
meson_options.txt
newlib/libc/picolib/machine/arc/CMakeLists.txt
newlib/libc/picolib/machine/arc/meson.build
newlib/libc/picolib/machine/arc/tls.c
scripts/cross-arc-zephyr-elf.txt

This adds general TLS support for targets without picolibc _set_tls support, and then adds specific ARC TLS _set_api support as well.

Add TLS support for ARC targets

---

CMakeLists.txt
meson.build
newlib/libc/stdlib/CMakeLists.txt
newlib/libc/tinystdio/CMakeLists.txt
newlib/libc/tinystdio/strtoi.h
picolibc.h.in
scripts/run-rv32imac
scripts/run-rv32imafdc

Shrink code a bit, including use of __builtin_{mul,add}_overflow for unsigned variants. Add cmake bits.

tinystdio: strtol et al improvements

---

newlib/libc/tinystdio/strtoi.h
newlib/libc/tinystdio/vfscanf.c
test/libc-testsuite/strtol.c

Directly sets the last character parsed to eliminate the 'ANY' flag.
This version now generates smaller code than newlib and Zephyr's minimal libc for all ARM targets while passing the Glibc test suite.

tinystdio: More strtou?l+ code improvements

---

newlib/libc/tinystdio/strtoi.h
newlib/libc/tinystdio/vfscanf.c
test/libc-testsuite/strtol.c

The code would accept @ and ` as legitimate digits, assigning them the value 9. Fix that by subtracting 1 from the character before oring in 0x20 to convert to lower case:
'0' is 0x30
'a' is 0x61
@ (0x40):
((0x40 - 1) | 0x20) + 0x30 - 0x61 + 11 - 0x30 = -0x17 (0xe9 unsigned)
` (0x60):
((0x60 - 1) | 0x20) + 0x30 - 0x61 + 11 - 0x30 = 0x29

tinystdio: strtoi/vfscanf bug parsing numbers

---

newlib/libc/include/ssp/unistd.h
newlib/libc/include/sys/config.h
newlib/libc/include/sys/unistd.h
newlib/libc/machine/nvptx/write.c
newlib/libc/stdio/fflush.c
newlib/libc/stdio/fmemopen.c
newlib/libc/stdio/fopencookie.c
newlib/libc/stdio/funopen.c
newlib/libc/stdio/fvwrite.c
newlib/libc/stdio/local.h
newlib/libc/stdio/open_memstream.c
newlib/libc/stdio/stdio.c
newlib/libc/stdio/stdio.h
newlib/libc/stdio64/stdio64.c
newlib/libc/tinystdio/freopen.c
newlib/libc/tinystdio/stdio_private.h
semihost/fake/fake_stub.c
semihost/machine/x86/e9_stub.c
semihost/read.c
semihost/write.c

Remove legacy cygwin hacks which set the buffer size and return value for read and write to int, switch them to the correct POSIX types, size_t for buffer size and ssize_t for the return value.

Switch read/write to posix types

---

meson.build

I spent many hours trying to debug why printff-tests and printff_scanff were failing for me. It turns out I had removed "-nostdlib" from my meson cross file and this in turn meant that cc.has_link_argument() returned false for any argument (since it errored out due to missing "-lc"). To avoid anyone else running into this problem in the future, emit an error at configure time if neither "--defsym" not "-alias" are accepted.

Emit a meson error if the linker doesn't support symbol aliases

---

cmake/TC-arm-none-eabi.ld
newlib/libc/picolib/machine/aarch64/tls.c
newlib/libc/picolib/machine/arm/tls.c
picocrt/machine/aarch64/crt0.c
picolibc.ld.in
test/tls.c

This was originally intended as a PR that only adds tests, but CI pointed out that the new tests break ARM builds, so I spent some time debugging and fixing ARM overaligned TLS (we need additional padding when setting the thread pointer).

Fix handling of ARM/AArch64 overaligned TLS 

---

cmake/TC-arm-none-eabi.ld
doc/linking.md
meson.build
picolibc.ld.in
scripts/cross-clang-old-riscv64-unknown-elf.txt
scripts/cross-clang-old-rv32imafdc-unknown-elf.txt
scripts/cross-clang-riscv64-unknown-elf.txt
scripts/cross-clang-rv32imafdc-unknown-elf.txt
scripts/cross-clang-thumbv6m-none-eabi.txt
scripts/cross-clang-thumbv7e+fp-none-eabi.txt
scripts/cross-clang-thumbv7m-none-eabi.txt

ld.lld rejects ALIGN_WITH_INPUT and the "i" memory region attribute.
However, the former is only needed due to a behaviour change in ld.bfd 2.32.2 - ld.lld uses an algorithm for LMA/VMA padding that ensures .data&.tdata have matching padding in RAM/flags.
Dropping latter attribute does not make any difference (unless maybe in cases where there are orphan sections), so we can also omit this for ld.lld.
See individual commit messages for more details.
Fixes #164

Allow linking with ld.lld

---

newlib/libm/common/math_config.h

Clang has a bug where it will crash for some inputs when built with assertions enabled. While this is a bug in Clang (and not in picolibc), it does reveal a possible issue in picolibc. So I figured I'd send a patch to picolibc as well as fixing it in Clang.
Fix to Clang: https://reviews.llvm.org/D138681
This is difficult to test: it requires a particular version of Clang with assertions enabled and I don't think it's reasonable to test that. So I did not include any. If this is not appropriate for picolibc, feel free to close this PR.

avr: work around Clang crash

---

hello-world/Makefile

CXXFLAGS is the commonly used name for options passed to the C++ compiler. CPPFLAGS is commonly used for C preprocessor flags.

hello-world: Rename CPPFLAGS -> CXXFLAGS to follow common practice

---

meson.build
newlib/meson.build

Leftovers after 55bc0abd6c2b89d697ca160b88f46d5951e9fba3 "Merge core C library with math library"

meson: Remove unused variable lib_m{target}

---

meson.build
picolibc.ld.in

Place all read-only or executable regions in flash, place all read-write sections in RAM.
The memory region attributes in the ld script are used to select a suitable region for orphan sections, or output sections where the destination address or region has not been set explicitly.
If a section matches _ANY_ of the attributes listed before the '!' and matches NONE of the attrbutes after '!' then it will be placed in that region. Therefore it does not make sense to add too many attributes here when we only have two regions to choose from. In particular, having the 'a' attribute listed for both regions will defeat the purpose of all the other attributes because ld will pick the first one for all ALLOCATABLE sections.
References:
- https://sourceware.org/binutils/docs/ld/MEMORY.html
- …

picolibc.ld: Reduce number of memory region attributes

---

COPYING.picolibc
newlib/libm/ld/ld128/e_rem_pio2l.h
test/long_double.c

The 128-bit IEEE long double function to compute remainder mod pi/2 for trig functions got
mangled at some point and some parens were shifted around compared with the same code in the 80-bit Intel version. Fix that, then tighten up the long_double test tolerances to validate that.

Fix bug in ieee 128-bit trig code

---

semihost/meson.build
semihost/sysconf.c
semihost/times.c
test/semihost/meson.build
test/semihost/semihost-times.c

times() uses sys_semihost_elapsed() for the time value. sysconf only supports _SC_CLK_TCK. Together, these can be used to measure elapsed time.

semihost: Provide implementations for times() and sysconf()

---

picolibc.ld.in

It was annoying to work with this file in my editor when the indentation was mixed between tabs and spaces on different lines.

picolibc.ld: Unify indentation

---

picolibc.ld.in

Copied from the default linker scripts in binutils. Having these sections explicitly listed in the linker script avoids warnings when linking with `--orphan-handling=warn`

picolibc.ld: Add debug-related sections

---

cmake/TC-arm-none-eabi.ld
newlib/libc/include/picotls.h
newlib/libc/picolib/inittls.c
picolibc.ld.in
scripts/cross-clang-old-riscv64-unknown-elf.txt
scripts/cross-clang-old-rv32imafdc-unknown-elf.txt
scripts/cross-clang-riscv64-unknown-elf.txt
scripts/cross-clang-rv32imafdc-unknown-elf.txt
scripts/cross-clang-thumbv6m-none-eabi.txt
scripts/cross-clang-thumbv7e+fp-none-eabi.txt
scripts/cross-clang-thumbv7m-none-eabi.txt
test/tls.c

.tbss might require padding after .tdata to ensure correct overall
alignment of data within that section. Add a new __tbss_offset value
in the linker script which sets the distance from the start of .tdata
to the start of .tbss.
Ensure that the space allocated for .tbss is positioned correctly by
explicitly setting the start address of .tbss_space to match .tbss.

picotls: Respect alignment requirements for .tbss

---

newlib/libc/tinystdio/conv_flt.c

Disabling C99 support replaces variable 'base' with a #define base, which then conflicts where conv_flt.c gets included.

tinystdio: Allow building without c99 float scanf support

---

CMakeLists.txt

_RETARGETABLE_LOCKING must be set to the inverse of __SINGLE_THREAD__, but cmake has no way to compute this value directly -- the set() command does not evaluate expressions. Instead, use an if() command to test __SINGLE_THREAD__ and select the correct value for _RETARGETABLE_LOCKING.

cmake: Fix single-thread build

---

picocrt/machine/x86/crt0-32.S
scripts/cross-clang-thumbv6m-none-eabi.txt
scripts/cross-clang-thumbv7e+fp-none-eabi.txt
scripts/cross-clang-thumbv7m-none-eabi.txt
scripts/do-lx106-configure

Debian testing now provides gcc 12.2.1. Look for libgcc there.

scripts: Update clang ARM scripts to use libgcc from gcc 12.2.1

---

newlib/libc/tinystdio/strtoi.h

Reorder the final code blocks to store the endptr before computing the final value. This lets the compiler generate ever so slightly shorter code.

tinystdio: Help the compiler generate shorter strto*l code

---

CMakeLists.txt

When building the library without thread local storage support, also make sure to disable the -ftls-model compiler flag and internal PICOLIBC_TLS apis.

cmake: Disable TLS_MODEL and _HAVE_PICOLIBC_TLS without TLS

---

newlib/libc/include/stdlib.h
newlib/libc/include/sys/cdefs.h

Starting with GCC version 4.5.0, the deprecated attribute allowed an optional string parameter which was displayed when the warning was emitted at compile time. Before that version, this parameter was not permitted and including it would cause a compile error.

stdlib: Support old GCC version without deprecated message

---

CMakeLists.txt
cmake/have-weak-attribute.c
newlib/libc/include/sys/cdefs.h
newlib/libm/common/math_config.h
newlib/libm/common/signgam.c

There was already autodetection support in meson for the `weak` attribute. Add that for cmake then use that in include/sys/cdefs.h instead of only using it for signgam in libm. This series also cleans up cdefs.h, removing unused macros and exposing autodetected features to non-__GNUC__ compilers.

Use compiler weak attributes instead of inline asm

---

newlib/libc/tinystdio/stdio.h

Remove stale doxygen comments. Remove 'extern' from function declarations. Use _fpos_t for fpos_t. Rearrange includes to make sure ssize_t is defined so it can be used instead of _ssize_t.

tinystdio: Clean up stdio.h

---

newlib/libc/include/malloc.h

The malloc.h header file references a bunch of stuff from sys/cdefs.h but fails to directly include it leading to errors when applications use this header without first including some header that happens to pull in sys/cdefs.h.
Closes: #432

stdlib: malloc.h requires <sys/cdefs.h>

---

newlib/libc/include/stdlib.h
newlib/libc/stdlib/nano-mallocr.c
newlib/libc/time/meson.build

three minor fixes:
1. Need wcsftime for libstdc++ for full wchar_t support
2. aligned_alloc was missing _NOTHROW attribute and only got that because the compiler knows about it
3. nano-mallocr didn't get the definition of aligned_alloc because it didn't include stdlib.h

various minor fixes

---

meson.build
newlib/libm/test/meson.build
newlib/testsuite/newlib.iconv/meson.build
newlib/testsuite/newlib.locale/UTF-8.c
newlib/testsuite/newlib.locale/meson.build
newlib/testsuite/newlib.search/meson.build
newlib/testsuite/newlib.stdio/meson.build
newlib/testsuite/newlib.stdlib/meson.build
newlib/testsuite/newlib.string/meson.build
newlib/testsuite/newlib.time/meson.build
newlib/testsuite/newlib.wctype/meson.build
picocrt/meson.build
test/libc-testsuite/meson.build
test/meson.build
test/semihost/meson.build

Somehow I missed that 'extract_objects' results could be used
in 'executable' and created static libraries for each of the
crt0 variants. Switch to using the relevant object files directly.

picocrt: Use generated crt0.o objects directly in tests

---

meson.build

The benefits are:
1. Allows picolibc to be built on systems without sed.
2. More readable code. The downside is that fs.read requires a newer meson version, but meson 0.57 is 2 years old at the time of writing.
source_root was deprecated in meson 0.56 but can trivially be replaced with current_source_dir.

Replace sed invocation with meson code

---

README.md
meson.build
newlib/libc/machine/microblaze/CMakeLists.txt
newlib/libc/machine/microblaze/abort.c
newlib/libc/machine/microblaze/meson.build
newlib/libc/machine/microblaze/strcpy.c
scripts/cross-microblazeel-zephyr-elf.txt
scripts/do-microblazeel-configure
scripts/test-microblaze.ld

Utilises the existing sources. Forked off of `zephyr`'s `picolibc` mirror to be able to collect consistent results from its CI.
Helps meson pick the `microblaze` cpu family from `microblazeel` tool.
`do-microblazeel-configure` then picks `cross-microblazeel-zephyr-elf.txt`
`zephyr` only supports `little-endian` so far _(last I checked)_, thus I never bothered to make Zephyr `sdk-ng` produce a big-endian toolchain. Hence no picolibc support for `microblaze-zephyr-elf` (big-endian is default).
No QEMU test set because QEMU invokation would need a `-hw-dtb` file such as 
https://github.com/zephyrproject-rtos/zephyr/blob/713b955801c44aadf2e66ed972b83da8ca03d837/boards/microblaze/qemu_microblaze/board-qemu-microblaze-demo.dtb
But @keith-packard and I agree that, that's the next step. Let's see …

machine: add Microblaze support for Zephyr toolchain (32-bit, little-endian)

---

newlib/libc/tinystdio/stdio_private.h
test/meson.build
test/test-atomic.c

I finally found docs on what _weak vs _strong means, and _weak is not what we need for ungetc -- that allows the operation to transiently fail, assuming it would be used in a loop of some sort.
And, add a test for atomics to at least make sure they work correctly in a trivial test.

Fix atomic use in ungetc, test atomics everywhere

---

semihost/open.c

Referencing #447.
Semihosting opens files in binary mode.  This assures transparent file operation between host and target.
Oops, are C++ style comments allowed in picolib?

Semihosting opens files in binary mode

---

.github/workflows/linux.yml
.github/workflows/variants
newlib/libc/stdio/vfprintf.c
newlib/libc/stdio/vfwprintf.c

Encounter error when use "-Dnewlib-fvwrite-in-streamio=true" option.

stdio: remove struct _reent in macro

---

.github/packages.txt
scripts/do-lx106-configure

The fix for https://bugs.debian.org/1032564 has landed in debian testing, so we can re-enable -Ddebug=true for
xtensa-lx106.

Re-enable xtensa debug

---

newlib/libm/ld/ld80/e_powl.c
test/math_errhandling.c
test/math_errhandling_tests.c

Eliminate a spurious exception generated on integer y values due to unnecessary conversion of float to int (i = w), the value of which was ignored. Fixes incorrect exceptions.
Make oflow/uflow cases with odd integer powers generate values with correct sign. Fixes incorrect return values.
Simplify control flow by making yoddint also depend on x being negative. Cleans up the code.
Also adds tests for these cases.

ld80: Fix several powl(x, oddint) cases

---

newlib/libm/math/s_pow.c
newlib/libm/test/pow_vec.c

E.g. known errors:
x = 0x1.000002c5e2e99p+0, y = 0x1.c9eee35374af6p+31 had an error of 639
ULP and is now correctly rounded.
x = 0x1.fffffd2e3e669p-1, y = 0x1.344c9823eb66cp+32 had an error of 428
ULP and is now correctly rounded.

libm: Fix pow for x close to 1, y between 2^31 and 2^64

---

newlib/libc/machine/aarch64/memchr.S
newlib/libc/machine/aarch64/strchr.S
newlib/libc/machine/aarch64/strchrnul.S
newlib/libc/machine/aarch64/strrchr.S

clang is unhappy with the redundant number, and only wants the "correct" way: [ARM docs](https://developer.arm.com/documentation/dui0801/l/A64-SIMD-Vector-Instructions/MOV--vector--to-general---A64-?lang=en)

Fix optimized aarch64 string functions with clang

---

zephyr/zephyr.cmake

libgcc doesn't make sense for armclang so limit link to just libc.

zephyr: only link libc on armclang

---

newlib/libc/include/sys/_types.h

The Arm Compiler doesn't define the type wint_t in stddef.h so define it in _types.h based on define __WINT_TYPE__.

Define wint_t type for the Arm Compiler

---

.github/workflows/variants-cmake
CMakeLists.txt
newlib/libc/posix/CMakeLists.txt
newlib/libc/posix/fnmatch.c

There were bugs in the names of the options in various places and how the relevant files were listed in the CMake files. Add tests to make sure things continue to work.

Cmake fixes

---

newlib/libc/tinystdio/CMakeLists.txt

The set of files included in tinystdio wasn't being adjusted based on the value of the _IO_FLOAT_EXACT option leaving a cmake build always using the precise floating point code.

cmake: Support _IO_FLOAT_EXACT option

---

newlib/libm/common/s_fma.c
newlib/libm/common/sf_fma.c
newlib/libm/ld/common/s_fmal.c

Clang enables conversion of 'a*b+c' into an FMA operation by default, which compiles the fallback implementation of fma and fmaf into infinite loops. Add '#pragma STDC FP_CONTRACT OFF' when building with clang to disable this behavior.
Closes: #467

libm/common: Disable FP contractions on clang for fma/fmaf/fmal

---

meson.build
newlib/libm/machine/powerpc/meson.build

Allow '-lgcc' to be overridden in the cross compilation control file when linking tests and other executables used during the build.

Use 'libgcc' cross compile property to select libgcc.a file

---

newlib/libc/include/string.h
newlib/libc/include/sys/features.h

This macro works like `_GNU_SOURCE`, `_BSD_SOURCE` and friends. When set, picolibc exposes the Zephyr C API. If `__ZEPHYR__` is set and no other `_*_SOURCE` macro is set, then picolibc automatically selects `_ZEPHYR_SOURCE`.

Add support for `_ZEPHYR_SOURCE`

---

cmake/picolibc.cmake

Older clang versions appear to use this flag to control handling of messages related to `__optimize__` attribute values.

cmake: Add -Werror=attribute-optimize when testing compiler support

---

.github/workflows/linux.yml
.github/workflows/variants
meson.build
newlib/libc/tinystdio/fmemopen.c
newlib/libc/tinystdio/meson.build
newlib/libc/tinystdio/sflags.c
newlib/libc/tinystdio/stdio_private.h

Two new functions that take a mode string were added, freopen and fmemopen. The former relies on POSIX I/O and so needed to only be built when posix-io=true. The latter still needs a way to convert the open mode string to the internal FILE operation flags. Do this by creating a new API, __stdio_sflags, which sits atop __posix_sflags when posix-io=true, but which directly uses a modified version of the __posix_sflags implementation when posix-io=false.
Closes: #486.

libc/tinystdio: Fix building with -Dposix-io=false

---

newlib/libc/include/sys/cdefs.h
newlib/libc/posix/fnmatch.c
newlib/libc/posix/regcomp.c
newlib/libc/search/hash_func.c
newlib/libc/stdio/nano-vfprintf_i.c
newlib/libc/stdio/nano-vfscanf.c
newlib/libc/stdio/vfprintf.c
newlib/libc/stdio/vfscanf.c
newlib/libc/stdio/vfwprintf.c
newlib/libc/stdio/vfwscanf.c
newlib/libc/stdlib/dtoa.c
newlib/libc/stdlib/gdtoa-gethex.c
newlib/libc/stdlib/strtod.c
newlib/libc/stdlib/strtodg.c
newlib/libc/time/strptime.c
newlib/libc/tinystdio/conv_flt.c
newlib/libc/tinystdio/strtoi.h
newlib/libc/tinystdio/vfprintf.c
newlib/libc/tinystdio/vfscanf.c
newlib/libc/xdr/xdr.c

Avoid placing an internal symbol in a globally visible header file.
Closes: #488.

cdefs.h: Use __PICOLIBC_FALLTHROUGH instead of FALLTHROUGH

---

test/meson.build

The posix console code requires a constructor to be called to initialize per-FILE locks. This makes it incompatible with the minimal crt0, so skip the test for that when posix console is in use.
Replaces #494

test: Skip constructor-skip test when using posix console

---

newlib/libc/include/sys/errno.h
newlib/libc/include/sys/lock.h
newlib/libc/misc/lock.c
newlib/libc/search/hash.c
newlib/libc/search/hash_bigkey.c
newlib/libc/search/hash_page.c
test/lock-valid.c

Move non-POSIX values EFTYPE, EPFNOSUPPORT, EHOSTDOWN and ETOOMANYREFS into __LINUX_ERRNO_EXTENSIONS__ blocks. Add missing LINUX errno values EHWPOISON, EISNAM, EKEYEXPIRED, EKEYREJECTED and EKEYREVOKED. Reformat to align comments vertically.

libc/include: Clean up sys/errno.h header

---

.github/workflows/variants
newlib/libc/stdio/vfprintf.c
newlib/libc/stdio/vfscanf.c
newlib/libc/stdio/vfwprintf.c
newlib/libc/stdio/vfwscanf.c
test/testcases.c

va_list might be declared as an array (as on x86_64), in which
case we must wrap the value inside a struct to support passing it
by address. Use va_copy to move it into the right place. This probably
messes up targets that do something in va_end.
On targets with sizeof(char *) > sizeof(int), the printf code that
attempts to stash intermediate values gets confused sometimes by *
arguments. Deal with this by just treating all 'int' args as 'char *'
in get_arg so that bits aren't lost. This assumes that these targets
align all arguments on char * instead of int boundaries.

libc/stdio: Fix legacy stdio positional arguments

---

meson.build
picolibc.ld.in
test/tls.c

picolibc.ld: Ensure .tdata alignment matches .tbss
If no TLS block has been assigned yet, picolibc uses the template inside
the binary directly. However, ld.lld only guarantees that .tdata/.tbss
are valid as a TLS template and not necessarily directly usable when using
picolibc's existing initialization logic. Add an explicit alignment
expression to the start of .tdata to ensure .tdata variables are at least
as aligned as the .tbss ones. This fixes the tls test when linking with
ld.lld while allowing to keep the single memcpy() call.
For context on linker behaviour: https://github.com/picolibc/picolibc/pull/411

Make lld work again for TLS

---

newlib/libm/common/math_config.h
newlib/libm/common/nexttowardf.c
newlib/libm/common/s_nextafter.c
newlib/libm/common/sf_nextafter.c
newlib/libm/ld/ld128/s_nextafterl.c
newlib/libm/ld/ld128/s_nexttoward.c
newlib/libm/ld/ld128/s_nexttowardf.c
newlib/libm/ld/ld80/s_nextafterl.c
newlib/libm/ld/ld80/s_nexttoward.c
newlib/libm/ld/ld80/s_nexttowardf.c

Make sure the compiler actually performs the computation being passed to one of the force_eval_ functions so that the right exceptions are generated.
This fixes various clang bugs with the nextafter/nexttoward functions where they were not raising the FE_UNDERFLOW exception.
Refer to discussion in #500

math: Add barriers in nextafter*/nexttoward* uses of force_eval*

---

newlib/libc/include/sys/config.h
newlib/libc/string/memccpy.c
newlib/libc/string/memchr.c
newlib/libc/string/memrchr.c
newlib/libc/string/rawmemchr.c
newlib/libc/string/stpcpy.c
newlib/libc/string/stpncpy.c
newlib/libc/string/strcat.c
newlib/libc/string/strchr.c
newlib/libc/string/strcmp.c
newlib/libc/string/strcpy.c
newlib/libc/string/strlen.c
newlib/libc/string/strncat.c
newlib/libc/string/strncmp.c
newlib/libc/string/strncpy.c

When the llvm address sanitizer is enabled while building the library, we need to bypass the optimized string functions which read past the end of the strings looking for null bytes.
Closes: #506

libc/string: Keep string code from reading out-of-bounds when asan enabled

---

picolibc.ld.in
scripts/do-native-configure

Making the linker script work with lld changed how the script enabled the ALIGN_WITH_INPUT mode for .tdata but missed that change for .data

picolibc.ld: Fixup for lld alignment changes

---

newlib/libc/include/sys/config.h
newlib/libm/test/meson.build

Missed the code to detect when GCC enables the address sanitizer.

Asan fixup

---

doc/linking.md

Thanks to Peter A. Jonsson for reporting this.
Closes: #510

doc: Remove a couple of spurious _ from a linking example

---

.github/do-linux
.github/linux-packages.txt
newlib/libc/iconv/ces/euc.c
newlib/libc/posix/regcomp.c
newlib/libc/search/hash.h
newlib/libc/tinystdio/vfscanf.c
newlib/libm/ld/math_private_openbsd.h
test/printf-tests.c
test/test-ubsan.c

This reverts commit 8dd225aa1469c03805617106020d494912c6d265.
Testing has been fixed; we can re-enable mips tests now.

Revert ".github: Disable mips/mipsel targets while Testing is broken"

---

.editorconfig
COPYING.picolibc
meson.build
newlib/libc/picolib/machine/arm/arm_tls.h
newlib/libc/picolib/picosbrk.c
newlib/libc/posix/dirname.c
newlib/libc/tinystdio/atod_engine.c
newlib/libc/tinystdio/atof_engine.c
newlib/libm/test/test.h
newlib/testsuite/include/check.h
newlib/testsuite/newlib.string/tstring.c
picocrt/machine/arm/crt0.c
picolibc.ld.in
scripts/cross-thumbv8_1m-none-eabi.txt
scripts/cross-thumbv8m_main_fp-none-eabi.txt
scripts/do-thumbv8_1m-configure
scripts/do-thumbv8m_main_fp-configure
scripts/run-arm
scripts/run-cortex-m33
scripts/run-cortex-m55
test/long_double.c
test/malloc_stress.c
test/math_errhandling_tests.c
test/timegm.c

This is more of a starting point for discussion than a final patch.
Set proper QEMU machine for some cortex-m* tests.
QEMU has specific boards for some cortex-m processors. Using them enables testing on QEMU without the virtm patch.
Added boot_flash to the link script.
The mps3-547 board has just 512 KB of flash at address 0. This is not enough to hold the math_test test. There is more memory at 0x0100_0000, but the interrupt vector has to stay at 0. To resolve this I added boot_flash memory region to hold the interrupt vector separately from the rest of the code. This modification to link script could also be useful to final users on arm targets, making them more likely to be able to use unmodified picolibc.ld.
Add cortex-m33 and cortex-m55 test configurations.
I had to create separate …

RFC: Add testing for additional arm targets.

---

scripts/run-arm

Dominik Wójt notes that we're using cortex-m55 for v8 DP mode, but explicitly skipping that for v8.1M DP. That wasn't caught in testing as GCC's current multilib setup doesn't include that target.

scripts: Simplify run-arm by making cortex-m55 handle all v8.1m

---

.github/Dockerfile-zephyr
.github/do-zephyr
.github/workflows/head-zephyr
.github/workflows/zephyr.yml
.github/zephyr
.github/zephyr-files.txt
.github/zephyr-sequence.txt
meson.build
newlib/libc/include/machine/ieeefp.h
newlib/libc/include/math.h
newlib/libc/machine/mips/sys/fenv.h
newlib/libc/picolib/machine/mips/meson.build
newlib/libc/picolib/machine/mips/tls.c
newlib/libm/common/math_config.h
newlib/libm/ld/math_private_openbsd.h
newlib/libm/test/math.c
picocrt/machine/mips/crt0.c
picocrt/machine/mips/meson.build
scripts/cross-mips-zephyr-elf.txt
scripts/do-mips-zephyr-configure
scripts/run-mips
semihost/machine/mips/meson.build
semihost/machine/mips/mips-semihost.h
semihost/machine/mips/mips_exit.c
semihost/machine/mips/mips_iob.c
semihost/machine/mips/mips_stub.c
test/testcases.c

This series includes a few MIPS-related fixes and a pile of MIPS enabling code for picocrt, picolib and semihost. With those, we can use the Zephyr toolchain to test all of the multilib configurations provided there.

Test MIPS support using Zephyr toolchain

---

.github/do-zephyr
newlib/libc/machine/arc/setjmp.S
scripts/cross-arc64-zephyr-elf.txt
scripts/do-arc64-configure
scripts/run-arc

Found and fixed a couple of setjmp/longjmp bugs on arc64. Then enabled testing under qemu.

Fix arc64 setjmp, then test with Zephyr toolchain

---

.github/do-zephyr
.github/zephyr-files.txt
picocrt/machine/nios2/crt0.c
picocrt/machine/nios2/meson.build
picolibc.ld.in
scripts/cross-nios2-zephyr-elf.txt
scripts/run-nios2
semihost/machine/nios2/meson.build
semihost/machine/nios2/nios2_close.c
semihost/machine/nios2/nios2_exit.c
semihost/machine/nios2/nios2_fstat.c
semihost/machine/nios2/nios2_lseek.c
semihost/machine/nios2/nios2_open.c
semihost/machine/nios2/nios2_read.c
semihost/machine/nios2/nios2_semihost.c
semihost/machine/nios2/nios2_semihost.h
semihost/machine/nios2/nios2_stat.c
semihost/machine/nios2/nios2_stub.c
semihost/machine/nios2/nios2_unlink.c
semihost/machine/nios2/nios2_write.c

Add nios2 semihosting and crt support, fix up the linker script and run tests in github CI.

Test nios2 builds using Zephyr toolchain

---

newlib/libm/fenv/fegetexceptflag.c
newlib/libm/fenv/fesetenv.c
newlib/libm/fenv/fesetexceptflag.c
newlib/libm/ld/common/s_fmal.c
newlib/libm/ld/common/s_frexpl.c
newlib/libm/ld/common/s_roundl.c
newlib/libm/ld/ld128/s_truncl.c
newlib/libm/ld/ld80/s_truncl.c
test/meson.build

* Make the stub fenv functions report "success" when possible.
* Lengthen one test timeout -- 128bit emulation on rv32e is slow

A couple minor math fixes

---

newlib/libc/picolib/picosbrk.c

Sbrk needs to be careful about types when the heap size is larger than the maximum value represented by ptrdiff_t. Use unsigned computations to make this work. This works as the end of the heap variable (brk) must lie within heap the address range.

picolibc: Support heap > 2GB on 32-bit targets

---

newlib/libc/posix/dirname.c

atod and atof work now, but dirname remains broken due to a compiler bug in -Os mode.

libc/posix: dirname is also broken on 12.3.1 for arm v8.1m

---

.github/linux-files.txt
.github/workflows/head
.github/workflows/head-zephyr
.github/workflows/linux.yml
.github/workflows/steps-head
.github/workflows/targets-cmake-linux
.github/workflows/targets-linux
.github/workflows/targets-zephyr
.github/workflows/zephyr.yml
newlib/libc/tinystdio/conv_flt.c
newlib/libc/tinystdio/vfprintf.c
newlib/libm/common/fma_inc.h
newlib/libm/common/s_fma.c
newlib/libm/common/sf_fma.c
newlib/libm/ld/ld80/s_nextafterl.c
newlib/libm/ld/s_fmal.c
newlib/libm/machine/m68k/fegetexceptflag.c
newlib/libm/machine/m68k/fegetround.c
newlib/libm/machine/m68k/feholdexcept.c
newlib/libm/machine/m68k/fesetenv.c
newlib/libm/machine/m68k/fesetexceptflag.c
newlib/libm/machine/m68k/fesetround.c
test/fma_gen.5c
test/libc-testsuite/strtol.c
test/long_double.c
test/test-fma.c

68881 and 8087 FPUs perform all computations in long double precision and then convert to target format. Emulate this for fma and fmaf by using fmal instead of doing computations in the target precision.
Enable testing of these formats, although qemu appears to have bugs with 68881 denorms which means skipping fmal tests on that target.

Fix fma/fmaf when __FLT_EVAL_METHOD__ == 2

---

test/rand.c

This fixes a -Wtype-limits warning where
the comparison is always true on architectures
with 16 bit ints.

test/rand.c: use int32_t as loop counter

---

newlib/testsuite/newlib.iconv/iconvjp.c
newlib/testsuite/newlib.iconv/iconvru.c

This eliminates compiler warnings about
unused arguments.

testsuite: silence unused argument warnings

---

test/math_errhandling_tests.c

Not really sure about this one, I arbitrarily chose 20 as value since the result of the multiplication then fits in a 16-bit int. If the constant 100 is chosen to hit some corner case on 32-bit architectures, my choice of 20 is not the right one.

math_errhandling_tests: 16-bit int fixes

---

CMakeLists.txt

GCC documents the option as '-include' in its
preprocessor options, and the meson build system
uses -include, so align the name with that.
With the double-dash option name, ccache detects
multiple inputs and refuses to cache.

CMakeLists.txt: use single-dash include option

---

.github/Dockerfile
.github/Dockerfile-zephyr
.github/workflows/head
.github/workflows/head-zephyr
.github/workflows/linux.yml
.github/workflows/steps-head
.github/workflows/zephyr.yml
.github/zephyr-packages.txt

The docker build cache will either hit everything or nothing, so put the commands together into a single RUN statement so everything ends up in the same layer.
Remove the apt-get-related data (packages + list files) after use.
Stop installing packages recommended by apt-get.
This saves 20 MB for the image built from Dockefile, and 640 MB for the image built from Dockerfile-zephyr.

Reduce size of Docker images

---

.github/workflows/head
.github/workflows/head-zephyr
.github/workflows/linux.yml
.github/workflows/zephyr.yml

Add compression options to the exporter.
Pick zstd as format since that can
run multiple threads to compress, and
use level 20 since that gives a significant
space improvement over 19.

CI: compress docker images

---

.github/dependabot.yml
.github/workflows/linux.yml
.github/workflows/macos.yml
.github/workflows/steps-fortify-source
.github/workflows/zephyr.yml
CMakeLists.txt

Add a dependabot configuration that automatically makes pull requests when Github actions have new versions available.
Add ccache support to CMakeLists.txt and the CI for macOS.

CI: use ccache on macOS

---

.github/zephyr-packages.txt

Add the libsndio7.0 package so qemu-system-nios2 in the Zephyr tests can run.

CI: make qemu-system-nios2 run again

---

.github/workflows/head
.github/workflows/head-zephyr
.github/workflows/linux.yml
.github/workflows/macos.yml
.github/workflows/zephyr.yml

When a PR gets updated, cancel any CI jobs
from the previous run. Let merge jobs complete
their runs, even if more PRs are merged after.

CI: cancel jobs when updating PRs

---

newlib/testsuite/meson.build

The compiler gives warnings when building
with -Dnewlib-iconv-encodings=none because
the iconv tests read outside array bounds
when the arrays are empty.
Only build iconv tests when there are some
encodings to actually test.
Fixes #545

newlib/testsuite: only test iconv when enabled

---

newlib/libc/misc/__dprintf.c
newlib/libc/posix/regerror.c
newlib/libc/search/hash_page.c
newlib/libc/time/gettzinfo.c
newlib/libm/common/math_config.h
newlib/libm/common/math_denorm.c
newlib/libm/common/math_denormf.c
newlib/libm/common/math_denorml.c
newlib/libm/common/math_err_divzero.c
newlib/libm/common/math_err_invalid.c
newlib/libm/common/math_err_may_uflow.c
newlib/libm/common/math_err_oflow.c
newlib/libm/common/math_err_uflow.c
newlib/libm/common/math_errf_divzerof.c
newlib/libm/common/math_errf_invalidf.c
newlib/libm/common/math_errf_may_uflowf.c
newlib/libm/common/math_errf_oflowf.c
newlib/libm/common/math_errf_uflowf.c
newlib/libm/common/math_inexact.c
newlib/libm/common/math_inexactf.c
newlib/libm/common/math_inexactl.c
newlib/libm/ld/math_errl_divzerol.c
newlib/libm/ld/math_errl_invalidl.c
newlib/libm/ld/math_errl_oflowl.c
newlib/libm/ld/math_errl_uflowl.c
newlib/libm/test/test.c
newlib/testsuite/newlib.time/tzset.c
test/tls.c

Here's another series of small patches which adjust the location of constants to move them from RAM to flash.
With this series, there are no more read-only variables that land in initialized RAM.

Move more constants out of RAM

---

test/tls.c

Use int32_t instead of int to avoid
overflows.

test/tls: fix for 16-bit int targets

---

newlib/libm/test/test.c
test/tls.c

The mask constant is larger than 16 bits,
so use an uint32_t for the mask variable.

libm/test: fix for 16-bit int targets

---

picocrt/machine/mips/crt0.c

dla is needed to load 64-bit addresses as la only handles 32-bit values.

picocrt/mips: Use 'dla' instead of 'la' on 64-bit targets

---

.github/workflows/head-zephyr
.github/workflows/zephyr.yml

The documented largest cache is wrong, so
fix that and increase the cache size
accordingly.

CI: increase ccache size for Zephyr jobs

---

test/printf-tests.c

This allows the test to link on msp430f1611.

printf-tests: use smaller buffers

---

.github/workflows/head
.github/workflows/head-zephyr
.github/workflows/linux.yml
.github/workflows/zephyr.yml

Increasing the compression level from 19
to 20 gives significant space savings
without increasing docker load times.
Increase the compression level to the max
since that will benefit every download
performed by the CI.
Compression level is documented, but it
does currently not have any effect
for the docker exporter. If level 22
turns out to take prohibitively long
when the parameter is no longer ignored,
this setting can be dialed back to 20.

CI: increase Docker compression level

---

.github/workflows/linux.yml
.github/workflows/variants
.github/workflows/zephyr.yml
meson.build
meson_options.txt
newlib/libc/stdio/findfp.c
newlib/libc/tinystdio/ultoa_invert.c
test/meson.build
test/printf_scanf.c

Provides custom divide+modulus code for use by printf on targets without hardware dividers. This custom code avoids requiring soft divide code, which can be useful if applications aren't otherwise using division of the relevant size.
For instance, arm targets do not have 64-bit division needed for decimal output when io-long-long is enabled.
The custom code uses the multiplication-by-reciprocal technique to approximate the division and then adjusts to provide an exact quotient and remainder.
This needs to be configured per-target but there isn't any convenient general-purpose tests available during the build. For now, there are examples which use architecture-specific preprocessor symbols on Arc, ARM and Risc-V to use the custom code on targets known to lack hardware division. For other …

libc/tinystdio: Replace %/ with fancy non-div using code on some targets

---

newlib/libc/stdlib/CMakeLists.txt
newlib/libc/stdlib/assert_func.c
newlib/libc/stdlib/assert_no_arg.c
newlib/libc/stdlib/meson.build

This avoids linking conflicts when applications define one of the helpers while picolibc uses another.

libc/stdlib: Split assert helpers into separate files

---

scripts/cross-msp430-unknown-elf.txt

Interrupt vectors differ between different msp430
models, so make it possible to provide the location and size.

msp430: make init/vector addr adjustable

---

meson.build
newlib/libc/picolib/machine/arm/read_tp.S
newlib/libc/picolib/machine/arm/tls.c
scripts/cross-msp430-unknown-elf.txt
scripts/cross-msp430.txt

Query GCC for the snippet that selects the library corresponding to the -mhwmult parameter, and
splice that into picolibc.specs.
This makes the tests not link on msp430 since
they are linked with -nostartfiles, so add -lmul_none in the libgcc config option in scripts since that
is not propagated outside picolibc.

meson.build: get -mhwmult selection from GCC

---

newlib/libc/picolib/machine/arm/read_tp.S
newlib/libc/picolib/machine/arm/tls.c

Hi,
Clang does not like the `mrc 15, ...` syntax - it allows only `mrc p15, ...`. GCC seems fine with it.
When compiling https://github.com/ARM-software/LLVM-embedded-toolchain-for-Arm for armv8r it errors with:
```
../../../../_deps/picolibc-src/newlib/libc/picolib/machine/arm/tls.c:63:10: error: invalid operand for instruction
63 |         __asm__("mcr 15, 0, %0, cr13, cr0, 3" : : "r" (tls - TP_OFFSET));
|                 ^
<inline asm>:1:6: note: instantiated into assembly here
1 |         mcr 15, 0, r0, cr13, cr0, 3
|             ^
```
and
```
../../../../_deps/picolibc-src/newlib/libc/picolib/machine/arm/read_tp.S:54:6: error: invalid operand for instruction
mrc 15, 0, r0, c13, c0, 3
^
```
So I changed the operand to p15. I hope it's correct.

picolib/arm: Fix mrc/mcr coproc operand syntax

---

meson.build

Clang will vary the multi-lib output depending on other compiler flags. When those flags are placed in the c-args option instead of the compiler specification itself, we'll need to include that value too.
Closes: #603

Include the c-args option value when querying multi-lib support

---

doc/printf-sample/.map
doc/printf-sample/Makefile
doc/printf-sample/printf.c
doc/printf.md
meson.build
newlib/libc/tinystdio/stdio.h
newlib/libc/tinystdio/ultoa_invert.c

Fix some gaps in the long long support, including a typo in stdio.h and missing picolibc.specs fragments. Update the docs to explain how variants work better.

Fixes and doc updates for printf/scanf long long variant

---

meson.build
scripts/cross-msp430-unknown-elf.txt

Make the generated link script honor the __boot_flash and __boot_flash_size variables as it does for e.g. __flash and __flash_size.

make boot_flash customizable from .ld file again

---

scripts/cross-aarch64-linux-gnu.txt

The .got table gets marked as writable but doesn't need to be. We want to stick it in read-only memory along with executable bits so the linker ends up warning about the unified segment being marked RWX. Silence the linker warning as I can't figure out how to fix it for real.

scripts: Silence warning about .got table when linking on aarch64

---

scripts/do-m68k-configure
scripts/do-m68k-unknown-elf-configure
scripts/do-nios2-configure
scripts/run-arm
scripts/run-m68k
scripts/run-nios2
semihost/machine/m68k/m68k_read.c
semihost/machine/nios2/nios2_read.c

The semihosting support for both of these can support stdio testing.

scripts: Enable test-stdin on m68k and nios2

---

meson.build
picolibc.ld.in

When sections having common phdr entry in the linker script were placed far away from each other, the resulting ELF file could be very big.
The thumb_v8_m_main_dp_hard variant in do-arm-configure was affected by this issue and the resulting ELF file was ~17 MB large.

linker script: move additional sections to separate phdrs

---

picolibc.ld.in

Baremetal LLVM libunwind references these symbols to find the unwind information, so we need to expose them in the linker script.

piclibcpp.ld: Provide the __eh_* symbols needed for libunwind

---

newlib/libc/tinystdio/fmemopen.c
test/meson.build
test/t_fmemopen.c

I was trying to run a program that uses fmemopen with picolibc and got unexpected EOF returns when reading a buffer.
It turned out picolibc was returning EOF on the first NUL character which is not compliant with POSIX.
After fixing this initial behaviour difference I tried running the NetBSD fmemopen  test to check compliance and fixed various other issues found while running that test. The test assumes some NetBSD-speicific behaviour that I did not implement here, so I lightly modified it with a few ifdefs.

Improve POSIX-compliance of fmemopen

---

newlib/libc/tinystdio/stdio.h

The defines are being checked for in the libc++ tests.

tinystdio: Add some missing defines in stdio.h

---

picolibc.ld.in

Having these be separate makes it easier to look at binary and see which sections contribute to total binary size. Additionally, it would allow for a correct PT_GNU_RELRO if picolibc.ld were to grow PIC support in the future.
This should not have any effect on the final binary layout, it only adds two more ELF section headers.

picolibc.ld.in: use separate sections for .rodata and .data.rel.ro

---

meson.build
picolibc.ld.in

Splitting data landing in flash resulted in the linker getting upset in a couple of ways.
First, the constructor/destructor arrays were no longer getting aligned via the ALIGN statement above them, resulting in the symbols being mis-aligned from the actual arrays.
Second, the constructors and destructors were somehow getting marked 'writable' which made the linker unhappy as that meant the contents of flash were marked both executable and writable.
Fix this up by stuffing the constructor/destructor arrays into the .text segment along with the ALIGN statement.

Re arrange flash layout to make linker happy

---

picocrt/meson.build

Use local variables to hold the c_args/link_args values shared across the picocrt targets instead of duplicating them in each usage. Remove the extra 'c_args' values as those are already in the 'value' array.

picocrt: Clean up meson compile/link args

---

newlib/libc/tinystdio/dtoa.h
newlib/libc/tinystdio/vfprintf.c

Share some code between skip_to_arg and vfprintf. Move float conversion selection code to dtoa.h.
Use _NEED_IO_FLOAT64 and _NEED_IO_FLOAT_LARGE instead of _NEED_IO_DOUBLE and NEED_IO_LONG_DOUBLE when determining how many possible exponent digits there are as those will skip tests on targets with smaller float ranges.

tinystdio: Clean up vfprintf. Avoid extra exponent width tests.

---

newlib/libc/time/tzset.c

Don't bother optimizing identical calls to tzset as that requires saving the previous argument in memory.

libc/time: Don't use malloc/free in tzset

---

picocrt/machine/riscv/crt0.c

I was debugging a misaligned load error and noticed that setting a breakpoint in _ctrap (using the QEMU gdb stub) did not work as expected due to missing/incorrect unwind info. This pull request updates the _trap function such that setting a breakpoint in _ctrap prints a backtrace that points to the actual bad instruction.
To test this I added `__builtin_trap()` to fclose() and ran the test-fopen test.
```
$ gdb -q test/test-fopen '-ex=b _ctrap' '-ex=target remote :1234' -ex=c -ex=bt
Reading symbols from test/test-fopen...
Breakpoint 1 at 0x80000058: file ../../picolibc/picocrt/machine/riscv/crt0.c, line 84.
Remote debugging using :1234
0x0000000000001000 in ?? ()
Continuing.
Breakpoint 1, _ctrap (fault=0x805feee8) at ../../picolibc/picocrt/machine/riscv/crt0.c:84
84 …
```

Adjust RISC-V crt0 _trap to enable GDB backtraces

---

newlib/libc/stdlib/setenv.c

According to POSIX, an empty string should be considered as an invalid name for environment variables, and the implementations should return -1 and set errno to EINVAL.
https://pubs.opengroup.org/onlinepubs/9699919799/functions/setenv.html
However, both picolibc and newlib support this currently in setenv. Perhaps it is underspecified in the ISO C standard. Otherwise it is not really clear to me if this is a feature or a bug.
Recycling the existing pattern from unsetenv(), this should work appropriately
Closes: #648

newlib: libc: setenv should consider empty string invalid

---

newlib/libc/tinystdio/atod_ryu.c
newlib/libc/tinystdio/strtod.c
newlib/libc/tinystdio/strtof.c
newlib/libc/tinystdio/strtoi.h
newlib/libc/tinystdio/strtold.c
newlib/libc/tinystdio/vfscanf.c

None of the tinystdio code actually uses ctype, so remove the includes.

tinystdio: Remove ctype.h includes

---

zephyr/zephyr.cmake

This is no longer necessary as Picolibc exposes the Zephyr API without needing it.
Closes: #649

zephyr: Remove explicit definition of _POSIX_C_SOURCE

---

newlib/libc/posix/regcomp.c
newlib/libc/posix/utils.h
zephyr/zephyr.cmake

Avoid using the math symbol in case that has gotten included somehow.
Closes: #647

posix: Change "INFINITY" constant in regex code to REGEX_INFINITY

---

newlib/libc/include/machine/fenv-softfloat.h
newlib/libc/machine/aarch64/machine/fenv-fp.h
newlib/libc/machine/arm/machine/fenv-fp.h
newlib/libc/machine/m68k/machine/fenv-fp.h
newlib/libc/machine/powerpc/machine/fenv-fp.h
newlib/libc/machine/riscv/machine/fenv-fp.h
newlib/libc/machine/sh/machine/fenv-fp.h
newlib/libc/machine/sparc/machine/fenv-fp.h
newlib/libc/machine/xtensa/machine/fenv-fp.h
newlib/libm/fenv/CMakeLists.txt
newlib/libm/fenv/fegetmode.c
newlib/libm/fenv/fesetmode.c
newlib/libm/fenv/meson.build

There were two functions which were generic and should be included in libm/fenv: fegetmode and fesetmode.
Then there was a machine-dependent function, fesetexcept, which none of the targets provided and which was getting replaced by the (incorrect) generic version.

math: Add back a few missing fenv functions

---

newlib/libc/tinystdio/CMakeLists.txt
newlib/libc/tinystdio/meson.build
newlib/libc/tinystdio/posixiob_stderr.c
newlib/libc/tinystdio/posixiob_stdin.c
newlib/libc/tinystdio/posixiob_stdout.c

Currently stderr is aliased to stdout. This PR adds stderr as a separate file with fd 2. I can put this behind a configuration option if you'd like. Thanks!

tinystdio: Add stderr as separate buffer

---

newlib/libc/tinystdio/bufio.c
newlib/libc/tinystdio/fread.c

Reading from stdin needs to flush stdout before blocking, and that requires comparing the FILE points with those global variables. To prevent that from pulling in an otherwise-unused FILE during linking, use weak versions of stdin/stdout for those operations. That means checking for NULL stdout, which does take additional instructions.

tinystdio: Use weak symbols for stdin/stdout read/flush test

---

newlib/libc/include/ctype.h

Libstdc++ doesn't have support for the small ctype code, rather it assumes that things are newlib compatible. We'll hack things here instead of fixing libstdc++.

ctype: Use legacy ctype bits with C++

---

newlib/libc/stdlib/nano-mallocr.c

When size_t and pointers have different sizes, the previous malloc_chunk struct would end up with unnecessary padding between them. Rework the code by removing the size field from malloc_chunk and then explicitly store the size before the malloc_chunk. This will save a bit of memory in every allocation by eliminating those padding bytes.
This patch also adopts changes from Alex Richardson's #686 that use cdefs.h macros that compute aligned sizes.

libc/stdlib: Rework nano malloc to avoid padding in chunk struct

---

newlib/libc/tinystdio/posixiob_stderr.c

It looks like I used the wrong fd for `stderr` (it should be 2, not 1) in a previous PR, sorry about that. I also noticed that the `extern` definitions of `stdout` can cause problems with linking, where the `stdout` variable does not get properly included in the final binary if it is not used by user code, even if it is used by `__bufio_get`. This causes its use by `__bufio_get` to perform unintended accesses of other data.
Thanks!

Fix stderr fileno and stdout/stdin linking

---

newlib/libc/tinystdio/bufio.c

__bufio_get wants to flush stdout when reading from stdin, but only if both stdin and stdout are actually being used by the application. The hack for this is to declare them as 'weak' symbols; if not used elsewhere in the application, they'll end up with address zero.
We detect that case by comparing the *address* of the symbols against NULL, not the value.
Replace the value check for stdout with a check of the address and add an address check for stdin before fetching that.

tinystdio: Check the *address* of weak stdin/stdout

---

meson.build
meson_options.txt
newlib/libc/picolib/machine/arm/arm_tls.h
newlib/libc/picolib/machine/arm/read_tp.S
newlib/libc/picolib/machine/arm/tls.c

The RP2040 has two cortex-m0 cores. Allocate an array of TLS base pointers in __tls and then use the CPUID register to index into that.
Closes: #695

picolib: Add (optional) rp2040 support to ARM TLS code

---

doc/using.md

Some third-party toolchains may have an expectation that a C library will provide all the headers necessary for user application compilation. Which makes some sense, but in reality there're dependencies between certain headers (or rather their contents) and capabilities of the compiler used in the toolchain.
Thus, let's warn poor users for toolchains which have too high expectations from the C library.

doc: List headers to be provided by the toolchain

---

newlib/libc/tinystdio/bufio.c
newlib/libc/tinystdio/fread.c

The fast-bufio path in fread has the same stdin/stdout semantics as found in __bufio_get, so the fix applied there for weak stdin/stdout needs to be applied to fread as well. Take advantage of this to copy the slightly more efficient test from fread to __bufio_get.

tinystdio: Mirror bufio stdin/stdout flush fix to fast fread

---

newlib/libc/tinystdio/fgets.c
test/meson.build
test/test-fgets-eof.c

According to the ISO/IEC_9899_1999, section:7.19.7.2 It is mentioned that when EOF is encountered and no characters were read into the array a null pointer is returned. In the fgets function in picolibc,
it always returned NULL when it reaches EOF even if characters were read and that the file is not empty.
Accordingly a flag was added that checks if the file is empty or not, there is an added "if" condition that checks on this flag, if EOF was encountered for whether NULL or the pointer to the array that was read will be returned. The case where it returns NULL occurs when EOF and no characters were read. This change checks and handles that fgets returns the pointer to the array correctly when it reaches EOF.
This is a simple testcase that shows the effect of this change:
```c
#include …
```

tinystdio: fgets returns NULL only when EOF is reached

---

newlib/libm/test/test.h
test/libc-testsuite/string.c

Bail if the test vector output file creation fails. This is not used during testing, only to re-generate the test vectors using a "known good" math library.
This fixes a warning generated by the compiler from the matching fclose call as without the check, that could be called with a NULL FILE pointer.

newlib/libm: Protect math vector generator from fopen failure

---

newlib/libc/include/time.h
newlib/libc/time/asctime.c
newlib/libc/time/asctime_r.c
newlib/libc/time/ctime_r.c
newlib/testsuite/newlib.time/asctime.c
newlib/testsuite/newlib.time/meson.build
newlib/testsuite/newlib.time/tzset.c

And update `time.h` to include the required array sizes so that we get compile-time checking. Also test to make sure asctime_r actually does bounds checking now.

libc/time: Perform result bounds checking in asctime_r

---

test/test-fgets-eof.c
test/test-ungetc-ftell.c

These two newly introduced tests both make a file called "testfile.dat". So if they're run concurrently in the same directory, one can overwrite the other's test file and cause a spurious test failure.
Other tests in this directory avoid this problem by defining a macro TEST_FILE_NAME to something unique to the test, and then using that macro consistently. I've updated these two tests to do the same thing.

Fix name collision between test-fgets-eof and test-ungetc-ftell

---

newlib/libc/tinystdio/CMakeLists.txt
newlib/libc/tinystdio/bufio.c
newlib/libc/tinystdio/fread.c
newlib/libc/tinystdio/freopen.c
newlib/libc/tinystdio/funopen.c
newlib/libc/tinystdio/fwrite.c
newlib/libc/tinystdio/meson.build
newlib/libc/tinystdio/stdio-bufio.h
newlib/libc/tinystdio/stdio.h
newlib/libc/tinystdio/stdio_private.h
test/CMakeLists.txt
test/meson.build
test/test-funopen.c

This is a lot like fdevopen, but with bulk APIs instead of simple get/put APIs. To make this work, the existing bufio layer needed to be extended to allow either an int or a pointer to be stored in the FILE for all of the callbacks.

tinystdio: Add funopen

---

newlib/libc/time/asctime_r.c
newlib/testsuite/newlib.time/asctime.c

Check these values before using the local array to avoid out-of-bounds accesses. Mimic glibc's behavior of using ??? for out-of-bounds values.
Add a test for glibc and picolibc checking this result.

time: Bounds check tm_wday and tm_mon in asctime_r

---

newlib/libc/tinystdio/fgetwc.c
newlib/libc/tinystdio/fputwc.c
test/meson.build
test/test-wchar.c

According to ISO/IEC 9899/1999 section 7.19.2: Streams
wide character input/output functions when applied to a stream should change the file orientation to be wide-oriented
Before this change wide character input/output functions were applied to
byte-oriented stream resulting in erroneous results handling wide characters
input/output to/from files.
Issue found by running [SuperTest by SolidSands](https://solidsands.com/products/supertest).

tinystdio: Set the file stream to wide orientation in fputwc/fgetwc functions

---

newlib/libc/include/sys/signal.h

When removing some pthread API definitions, I unintentionally removed elements of 'struct sigevent' which are required by POSIX.
Closes: #754

include: Restore missing members of struct sigevent

---

newlib/libc/search/qsort.c
newlib/libc/string/xpg_strerror_r.c

Don't try to use typeof to match the definitions as those won't actually match if the library is built with -D_GNU_SOURCE=1.
Closes: #758

libc: Don't try to be clever when declaring __bsd_qsort_r and __xpg_strerror_r

---

newlib/libc/tinystdio/dtox_engine.c
test/testcases.c

The missing MSB in the significand caused the 'odd' check to fail, thus failing to round 0x1.8 to 0x2. Insert the implicit MSB into the significand so that the existing round-to-even code worked correctly.
That required moving the NAN/INF checks before adding the MSB.
Doing this insertion removed the need for the special case for the leading digit of the result, along with the special case for rounding that digit as the significand now includes the MSB.
Closes: #764

tinystdio: Correct printf %a round-to-even with zero precision

---

newlib/libc/tinystdio/dtoa.h
newlib/libc/tinystdio/dtoa_engine.c
newlib/libc/tinystdio/dtoa_ryu.c
newlib/libc/tinystdio/ftoa_engine.c
newlib/libc/tinystdio/ftoa_ryu.c
newlib/libc/tinystdio/vfprintf.c
test/printf_scanf.c
test/testcases.c

The original floating point output code relied on 'DTOA_CARRY' semantics where the low-level conversion code would punt some rounding operations up to vfprintf. This caused double rounding, and when the fraction rounded up to 0.5, the vfprintf rounding would round that again to 1.0.
All of the conversion functions now perform correct rounding internally, so the DTOA_CARRY mechanism is no longer necessary.
This also allows the conversion functions to return zero digits when the result rounds to zero as vfprintf no longer looks at the first digit to deal with DTOA_CARRY stuff.
Closes: #766

tinystdio: Eliminate double rounding in %f printf

---

newlib/libc/stdlib/malloc-posix_memalign.c
newlib/libc/stdlib/mallocr.c
newlib/libc/stdlib/meson.build
test/malloc.c

The two allocators mallocr.c and nano-mallocr.c mostly support the same set of functions, but posix_memalign is an exception: nano-mallocr has an implementation of it, but mallocr doesn't. This means the available API changes depending on whether you asked for a fast or a small memory allocator.
mallocr does support aligned memory allocation, via other APIs. So posix_memalign can be implemented as a wrapper on the existing API, just as it is in nano-mallocr.

mallocr.c: add an implementation of posix_memalign().

---

newlib/libc/tinystdio/vfscanf.c
test/meson.build
test/test-vfscanf-percent-a.c

After this change, %a & %A is correctly handled in vfscanf
Issue found by running [SuperTest by SolidSands](https://solidsands.com/products/supertest).

tinystdio: Enable %a format specifier in vfscanf

---

newlib/libc/tinystdio/freopen.c

`freopen` should reset the unget buffer to ensure subsequent input operations such as scanf work correctly. The unget buffer was not being reset, causing issues when tests are run consecutively.

tinystdio: Fix freopen to reset unget buffer

---

newlib/libc/tinystdio/dtox_engine.c
newlib/libc/tinystdio/freopen.c
newlib/libc/tinystdio/vfprintf.c
test/testcases.c

The conversion returns the number of fraction digits generated (ndig - 1); we need to remember the number of fraction digits desired in case that is larger so we can pad with zeros.
Closes: #775 
Reported-by: Ahmed Shehab <shehab@synopsys.com>

tinystdio: Don't limit %a precision

---

newlib/libc/tinystdio/bufio.c

The __bufio_close() function used to discard the return value of the semihost, so this return value is now saved in a variable to be returned. It Will return -1 if the file has been closed before.

tinystdio: fclose issue if called more than once

---

meson.build
newlib/libc/tinystdio/bufio.c

Instead of attempting to detect the lld version by checking for a specific compiler flag, just assume the clang version is the same as the lld version.
Closes: #773

clang: Adjust lld version detection method

---

meson.build
newlib/libc/ctype/isblank.c
newlib/libc/include/ctype.h
newlib/libc/tinystdio/bufio.c
test/meson.build
test/test-ctype.c

In non-C locales, isblank is supposed to return true for locale-specific characters for which isspace is true and are used to separate words within a line of text. That's what the _B bit does in the ctype tables. That bit is also used by 'isprint', which should not include tab, so we need an explicit test for tab in isblank.
Closes: #778

ctype: Fix isblank for non-C locales

---

newlib/libc/tinystdio/conv_flt.c
newlib/libc/tinystdio/ldtox_engine.c
newlib/libm/ld/common/e_lgammal.c
scripts/run-riscv
test/libc-testsuite/sscanf.c
test/printf-tests.c
test/testcases.c

Handle limited input width in the format spec when looking for nan and inf(inity) values.
Add tests for both of these values in both signs.

tinystdio: Support nan/inf values in float scanf

---

newlib/libc/include/assert.h

As of commit 5e4d0c80f49b4ef, Internal functions like `__assert` and `__assert_no_args` are declared using the C `_Noreturn` keyword. In C++ mode, <sys/cdefs.h> redefines that keyword to the C++-style `[[noreturn]]` attribute. But <assert.h> doesn't include <sys/cdefs.h>, so you don't reliably get the intended one of those two.
This can cause a compile failure, if you compile a C++ source file that includes <assert.h>, then <limits.h>, then <assert.h> again (perhaps without noticing, because they're transitively included from other files in that sequence). The first include of <assert.h> defines those functions with the compiler's built-in `_Noreturn`, and the second one defines them with `[[noreturn]]`, because in between, <limits.h> included <sys/cdefs.h>, which redefined `_Noreturn`. …

Add missing include of <sys/cdefs.h> from <assert.h>.

---

meson.build

This fixes the detection of ld.lld 15 which previously failed
unconditionally since the argument was being passed to the compiler and
not forwarded to the linker.
However, even with -Wl, this check fails since we are linking with
-nostartfiles and thus ld.lld complains about missing _start. We can work
around this problem by also passing --version, which ensures that we get an
error for unknown arguments and a zero exit code if all arguments exist.
Fixes https://github.com/picolibc/picolibc/issues/773

meson: Add missing -Wl, prefix to cc.has_link_argument() call

---

.github/do-build
meson.build
meson_options.txt
newlib/libc/include/arpa/meson.build
newlib/libc/include/meson.build
newlib/libc/include/rpc/meson.build
newlib/libc/include/sys/meson.build
newlib/libc/machine/aarch64/sys/meson.build
newlib/libc/machine/arm/sys/meson.build
newlib/libc/machine/m68k/sys/meson.build
newlib/libc/machine/mips/sys/meson.build
newlib/libc/machine/powerpc/sys/meson.build
newlib/libc/machine/riscv/sys/meson.build
newlib/libc/machine/sh/sys/meson.build
newlib/libc/machine/sparc/sys/meson.build
newlib/libc/machine/x86/sys/meson.build
newlib/libc/machine/xtensa/sys/meson.build
newlib/libc/stdio/meson.build
newlib/libc/stdio/sys/meson.build
newlib/libc/tinystdio/meson.build
semihost/meson.build

This is a three/way (true/false/auto) option which selects whether to validate the include files for correctly including sys/cdefs.h. When set to 'auto', then these tests are enabled if the regular library tests are enabled.

Control sys/cdefs checking with new tests-cdefs option

---

semihost/lseek.c
semihost/semihost-private.h
semihost/semihost.h
semihost/sys_close.c
semihost/sys_exit.c
semihost/sys_exit_extended.c
semihost/sys_flen.c
semihost/sys_iserror.c
semihost/sys_istty.c
semihost/sys_open.c
semihost/sys_read.c
semihost/sys_remove.c
semihost/sys_seek.c
semihost/sys_system.c
semihost/sys_tmpnam.c
semihost/sys_write.c

These functions make it easier to call the semihosting functions without having to declare a local struct in each caller.
Since there is only one call with 4 indirect parameters, I did not add a sys_semihost4 wrapper.

semihosting: reduce code duplication for calls with indirect arguments

---

COPYING.picolibc
newlib/libc/machine/riscv/strcmp.S
scripts/cross-rv32imac_zicsr_zbb.txt
scripts/do-rv32imac-configure

Optimize strcmp by calling orc.b (OR-Combine) instruction when Zbb extension is supported instead of 4 instructions to detect if zero byte is exist in word

strcmp optimization for riscv

---

newlib/libc/tinystdio/conv_flt.c
test/libc-testsuite/sscanf.c

Quoting from C standard part 7.19.6.2
> `a,e,f,g` Matches an optionally signed floating-point number, infinity, or NaN, whose format is the same as expected for the subject sequence of the `strtod` function. The corresponding argument shall be a pointer to floating.
Regarding `strtod`, quoting from C standard part 7.20.1.3
> A character sequence `NAN` or `NAN(n-char-sequence)`, is interpreted as a quiet NaN, if supported in the return type, else like a subject sequence part that does not have the expected form; the meaning of the n-char sequences is **implementation-defined**.

tinystdio: handling `"nan(n-sequence char)"` by `scanf()` family & `strtod()`

---

meson.build

I found that toolchains that have sysroot could not find picolibc includes or libs
In my case:
`%R` is `/home/alex/.espressif/tools/riscv32-esp-elf/esp-13.2.0_20240305.3-2cc49e8/riscv32-esp-elf/bin/../riscv32-esp-elf/`
but picolibc installed here: `/home/alex/.espressif/tools/riscv32-esp-elf/esp-13.2.0_20240305.3-2cc49e8/riscv32-esp-elf/picolibc`
In case `specs_prefix_format = '%:getenv(GCC_EXEC_PREFIX ../../@0@)'` all works fine. With this change `specs_prefix_format = '%:getenv(GCC_EXEC_PREFIX ../../@0@)'` and `specs_prefix_format = '%R/../@0@'` should point to the same directory... But I'm not sure that it's true for all GCC versions, I tested only with v14.1

fix specs_prefix_format to point to root toolchain's directory

---

newlib/libc/tinystdio/vfprintf.c
test/libc-testsuite/snprintf.c

Support for `%hn`, `%hhn`, `%ln` and `%lln`
Extends the handling of the `%n` specifier to support different integer types, including `%hn` (short) and `%hhn` (char), `%ln` (long) and `%lln` (long long), . This ensures correct and consistent behavior for various specifier types.
This fix addresses and resolves the issue #804 
Issue found by running [SuperTest by SolidSands](https://solidsands.com/products/supertest).

tinystdio: Fix handling `%n` in vfprintf.c

---

cmake/picolibc.cmake

Add -Werror=implicit-function-declaration to compile options used to check if a builtin function is supported.
If fixes an issue with detection for LLVM, when only warrning is "use of unknown builtin" is retured.
It fixes https://github.com/picolibc/picolibc/issues/805

cmake: improve builtin functions detection

---

newlib/libc/locale/newlocale.c

Updated `newlocale` function to handle empty, "C" and "POSIX" locale strings when `_MB_CAPABLE` is not defined.
The function now returns the "C" locale structure for these valid locales. For any other locale string, it sets `errno` to `EINVAL` and returns `NULL`, ensuring that an exception is raised in `C++` when using `std::locale`.

Ensure invalid locale strings raise an exception

---

picocrt/machine/aarch64/crt0.c

This caused register values to be printed left-shifted by 4, with the least significant digit repeated.

AArch64: Fix off-by-one in exception handler

---

meson.build
test/meson.build

For ARM, when using clang and compiler-rt, some tests fail because the C library contains calls to the __aeabi_memcpy* functions, which are defined in libgcc or compiler-rt. To make these work, compiler-rt needs to be after libc on the linker command line.

Link compiler-rt after libc in tests

---

test/libc-testsuite/meson.build

This is a follow-up patch of [#823](https://github.com/picolibc/picolibc/pull/823).
The same error mentioned in that Pull Request happens in the libc-testsuite. It turns out that the library order must also be adjusted in the meson.build file under the specific test suite.

Link compiler-rt after libc in libc-testsuite

---

newlib/libc/include/unctrl.h

Looks like I missed a couple of __IMPORT removals in bd3ad59.
Reported-by: Pablo Martínez
Closes: #835

libc: Clean up missed __IMPORT in unctrl.h

---

cmake/have-alias-attribute.c
meson.build
newlib/libc/tinystdio/vfscanf.c

common symbols cannot be aliased using the 'alias' attribute, so compilers which don't use -fno-common by default would complain when the have-alias-attribute.c check is build as that used a bare 'int x;' definition. Change that to an initialized value so that it is never a common symbol.
This series also includes a fix for the backwards-compatibility path in vfscanf which is triggered when the alias attribute is not supported.

cmake: Use non-common symbol for 'alias' attribute check.

---

newlib/libc/picolib/machine/aarch64/interrupt.c

The bottom 11 bits of VBAR_ELx are reserved, so the vector table must be 2048 bytes aligned, not just 1024 byte.

Align AArch64 vector table to 2048 bytes

---

picocrt/machine/x86/crt0-32.S
picocrt/machine/x86/crt0-64.S

Before clang-12, the built-in x86 assembler seems to treat prefixes as separate instructions. This meant that it wouldn't allow them on the same source line as the rest of the instruction. Split out the 'cs' prefix used in the x86 crt0 code to a separate line so that old clang versions can also assemble the code.
Closes: #849

picocrt: Adapt x86 crt0 code for old clang assembler

---

newlib/libc/include/time.h

The commit 5e4d0c80f49b4efe8be85e36b5e85d65bd343214 made gmtime_r(), which was previously always visible, only visible to POSIX.
Since gmtime_r() is part of the allowed non-standard libc functions in the Zephyr Coding Guidelines Rule A.5, make it also visible to Zephyr.

time: Make gmtime_r() visible to Zephyr

---

newlib/libc/include/uchar.h

This patch adds a macro guard around the typedefs for `char16_t` and `char32_t`.
These two types have become built-in in C++ starting from C++11. Because of that, the presence of the typedefs leads to an error as the types are already defined.
For C++11 or later, there's a difference in how libstdc++ and LLVM's libcxx use the C library's `uchar.h`. The former only includes the C library's `uchar.h` under certain conditions, whereas libcxx always does.
In the case of libcxx, this introduces a problem since picolibc's `uchar.h` has the typedefs unconditionally. Glibc, on the other hand, has them under a macro guard called `__USE_ISOCXX11`, defined as `defined __cplusplus && __cplusplus >= 201103L`
([link](https://sourceware.org/git/?p=glibc.git;a=blob;f=wcsmbs/uchar.h;h=7123f46500ef2162f2142 …

Define char16_t and char32_t in uchar.h conditionally

---

newlib/libc/include/uchar.h

Following up on commit d55527c12b25cc8bf219053195b1723600c1c09f, this patch also puts the `char8_t` typedef under a macro check.
From C++20, `char8_t` is a builtin type, so in that case the typedef must not be present. The C++ spec has a macro specific to check if `char8_t` is builtin. This macro is called `__cpp_char8_t`.

Define char8_t conditionally

---

newlib/libc/time/CMakeLists.txt

This file was left out of the cmake build.

time: Build wcsftime.c when using cmake

---

newlib/libc/ctype/ctype_.c
newlib/libc/include/ctype.h

Update the `_CTYPE_DATA_0_127` macro to include `_B` flag for the horizontal tab character (0x09), ensuring it is correctly recognized as a blank character.  
This change ensures that both horizontal tab and space characters are appropriately classified as blank character.

Classify horizontal tab as a blank character

---

meson.build

Seems like adding the 'long-long' option to the conf_data.set() options for 'tinystdio' was accidentally missed. This leads '_FORMAT_DEFAULT_LONG_LONG' not being set when using the 'format-default=long-long' option, which ultimately leads to the 'vfprintf' etc functions not being registered properly:
picolibc/newlib/libc/tinystdio/printf.c:41: \
undefined reference to `vfprintf'
Fix this by adding in the missing entry for the 'long-long' variant.
Fixes: ca70b2a7ad8b ("libc/tinystdio: Add 'long-long' printf/scanf variants")

meson: Add missing long-long option in conf_data.set for tinystdio

---

newlib/libc/tinystdio/CMakeLists.txt
newlib/libc/tinystdio/asnprintf.c
newlib/libc/tinystdio/asprintf.c
newlib/libc/tinystdio/meson.build
newlib/libc/tinystdio/stdio.h
newlib/libc/tinystdio/stdio_private.h
newlib/libc/tinystdio/vasnprintf.c
newlib/libc/tinystdio/vasprintf.c
test/printf-tests.c

These are like asprintf/vasprintf except they permit an application to use a pre-allocated buffer; if that overflows, only allocating space when that overflows.

tinystdio: Add asnprintf and vasnprintf

---

newlib/libc/locale/newlocale.c

- Updated newlocale function to handle empty string `""` as a valid locale input.
- If the locale is an empty string, the function now returns the default C locale `__get_C_locale`.
- Ensures compatibility with cases where locale `""` is expected to resolve to the default locale.
- Added error handling for unsupported configurations when `_MB_CAPABLE` is not defined.
This change improves compliance with locale handling expectations and provides better support for default behavior in minimal configurations.

Support locale ("") in newlocale implementation

---

newlib/libc/include/machine/ieeefp.h

Add ieeefp define for TriCore architecure. Used for example with HighTec Clang Compiler or gcc.

include: Add ieeefp define for TriCore architecture

---

.github/do-linux
.github/do-test
.github/linux-files.txt
.github/linux-packages.txt
meson.build
meson_options.txt
picocrt/machine/aarch64/crt0.S
picocrt/machine/aarch64/crt0.c
picocrt/machine/aarch64/meson.build
picocrt/meson.build
scripts/cross-clang-aarch64-none-elf-fvp.txt
scripts/do-clang-aarch64-fvp-configure
scripts/run-aarch64-fvp

The AArch64 FVP (Fixed Virtual Platform) models differ from QEMU in a few ways which affect the crt0 code:
* The memory map is different, so needs different page tables.
* They boot up at EL3, instead of EL1, so we need to set the EL3 versions of the system registers.
This change also introduces new CI scripts for running tests on FVPs.
Based on work from PR #852.
Co-authored-by: Oliver Stannard <oliver.stannard@arm.com>

Add bootcode and CI scripts for AArch64 FVPs

---

newlib/libc/include/stdlib.h
newlib/libc/stdlib/ignore_handler_s.c
newlib/libc/stdlib/set_constraint_handler_s.c
newlib/libc/string/memcpy_s.c
newlib/libc/string/strcat_s.c
newlib/libc/string/strcpy_s.c
newlib/libc/string/strncat_s.c
newlib/libc/string/strncpy_s.c
newlib/libc/tinystdio/sprintf_s.c
newlib/libc/tinystdio/stdio.h
newlib/libc/tinystdio/vfprintf.c
newlib/libc/tinystdio/vsnprintf_s.c

Updating the Annex-K functions to use the compiler-specific `__restrict` keyword instead of the standard `restrict`. 
This change ensures better compatibility with environments where `restrict` is not available or where `__restrict` is the preferred aliasing hint, such as in certain C++ or pre-C99 contexts.

Use `__restrict` instead of `restrict` in Annex-K functions

---

scripts/duplicate-names

FreeBSD's nm labels some symbols with 'N' that aren't global names. Ignore these when looking for duplicate symbols.

scripts: Fix duplicate-names script for FreeBSD

---

meson.build
newlib/libc/stdlib/chacha_private.h
newlib/libc/time/asctime_r.c
newlib/libc/tinystdio/stdio.h
newlib/libm/test/meson.build
picolibc.specs.in
scripts/do-configure
test/libc-testsuite/meson.build
test/meson.build

A selection of minor fixes
1. Fix warnings about overwriting linker scripts during meson run
2. GCC warning fixes
3. Support new --printf= option for gcc
4. Ignore rwx segment warnings during link
5. Remove picolibc/ in do-configure script when -Dsystem-libc=true
6. Use link_with when building tests to make 'ninja clean' work

Fixes for dev version of gcc, 'ninja clean' and -Dsystem-libc=true

---

picocrt/machine/aarch64/crt0.c
picocrt/machine/arm/crt0.c

We need changes in both Arm/AArch64 bootcode in order for the -mno-unaligned-access to work.
We need to enable the Alignment Check bit in the System Control Register (SCTLR) which is the Bit 1 (A) and it turn on alignment fault checking for data accesses . If an unaligned data access occurs, an alignment fault exception will be generated.
Also need to disable the Unaligned Access Enable(U) bit in the System Control Register (SCTLR). As a result, unaligned data accesses will generate an alignment fault exception.
This is based on the changes from #874 .
Co-authored-by: Simi Pallipurath <simi.pallipurath@arm.com>

[ARM/AARCH64] BootCode Changes to enable the Alignment Check bit and disable the unaligned access bit

---

.github/do-linux
.github/linux-files.txt
meson.build
newlib/libc/include/machine/ieeefp.h
newlib/libc/include/machine/setjmp.h
newlib/libc/machine/loongarch/asm.h
newlib/libc/machine/loongarch/machine/_fpmath.h
newlib/libc/machine/loongarch/machine/fenv-fp.h
newlib/libc/machine/loongarch/machine/fenv.h
newlib/libc/machine/loongarch/machine/math.h
newlib/libc/machine/loongarch/machine/meson.build
newlib/libc/machine/loongarch/meson.build
newlib/libc/machine/loongarch/setjmp.S
newlib/libc/tinystdio/stdio.h
picocrt/machine/loongarch/crt0.c
picocrt/machine/loongarch/meson.build
scripts/cross-loongarch64-unknown-elf.txt
scripts/do-configure
scripts/do-loongarch64-configure
scripts/run-loongarch64
semihost/machine/loongarch/meson.build
semihost/machine/loongarch/semihost-loongarch.S

Hi All,
This PR implemented initial support for LoongArch.
Currently, only LoongArch 64 build is supported as upstream LoongArch32 ABI is not ratified yet, but all implementations are 32bit aware and build tested against downstream toolchain.
It requires a custom `loongarch64-unknown-elf` toolchain to build, my `ct-ng` config built for current crosstool-ng master:
```
CT_CONFIG_VERSION="4"
CT_EXPERIMENTAL=y
CT_ARCH_LOONGARCH=y
CT_ARCH_USE_MMU=y
CT_ARCH_ARCH="loongarch64"
CT_LIBC_NONE=y
CT_CC_GCC_LIBSTDCXX_VERBOSE=m
CT_CC_LANG_CXX=y
CT_DEBUG_GDB=y
CT_GETTEXT_NEEDED=y
```
For QEMU testing, a patch to enable semihosting is also required:
https://lore.kernel.org/qemu-devel/20241222-semihosting-v1-1-8a770df60e9c@flygoat.com/
All tests are passing on my side:
```
ninja test
[0/1] Running all …
```

Initial LoongArch support

---

newlib/libc/include/sys/cdefs.h
newlib/libc/locale/setlocale.h
newlib/libc/stdio/findfp.c
newlib/libc/stdio/local.h
newlib/libc/stdio/nano-vfprintf.c
newlib/libc/stdio/stdio.h
newlib/libc/stdio/vfprintf.c
newlib/libc/string/str-two-way.h
newlib/libc/xdr/xdr_private.h
newlib/libm/common/math_config.h
newlib/libm/common/math_err_with_errno.c
newlib/libm/ld/math_errl_with_errnol.c
newlib/libm/ld/math_private_openbsd.h
picocrt/crt0.h
picocrt/machine/arm/crt0.c

We have to use a separate ARM-mode function, _set_stacks, to perform processor mode selection as the thumb-1 ISA doesn't include the msr instruction. But, by the time we get there, the compiler may have used the stack for some other operations. So, we want to avoid smashing the stack pointer. Leave the SVC mode stack pointer alone, and only set the other stack pointers. Then, switch back to SVC mode.
This is a simplified version of #897, but still doesn't resolve the fact that all of these stacks overlap, which only works because the only usage we've got with the current code is to terminate on any exception.

picocrt/arm: Don't reset SP after _start on thumb-1 targets

---

.github/linux-files.txt
.github/zephyr-files.txt

These are built in CI instead of by hand

.github: Switch most CI tools to picolibc-ci-tools

---

.github/Dockerfile
.github/Dockerfile-zephyr

Debian testing is currently missing some critical packages during a gcc-14 update adventure. Switch to unstable until that gets resolved.

.github: Switch to debian:sid while debian:testing is broken

---

newlib/libc/machine/or1k/CMakeLists.txt
newlib/libc/machine/or1k/meson.build

With these build files added, picolibc successfully builds for the OpenRISC 1000 (or1k) architecture.

or1k: Add or1k build files

---

test/test-except.c

`.hword` is not endianness agnostic, thus this patch replaces it with `.inst.n` which is.

Modify test-except to work with ARM M-profile big endian

---

newlib/libc/tinystdio/bufio.c

Forgot to advance buffer pointer when making mutiple passes to send whole buffer.

tinystdio: fix bug in bufio flush

---

newlib/libc/include/machine/_default_types.h
newlib/libc/include/sys/_intsup.h
newlib/libc/include/sys/cdefs.h
newlib/libc/stdlib/nano-mallinfo.c
newlib/libc/tinystdio/stdio-bufio.h
newlib/libc/tinystdio/stdio.h

This patch-set contains fixes for various issues encountered while experimenting with picolibc building with GCC v4.1.2.

Improve support for old versions of GCC

---

newlib/libc/stdlib/nano-malloc.h

This fixes crashes I was seeing with C++ code on RISCV-64 where Clang assumes that the result of operator new is at least 16 byte aligned instead of the current 8 byte alignment.
I noticed this because the code I was running was asserting for sufficient alignment, but this also could cause other difficult to debug issues if the compiler optimizes based on that 16-byte alignment assumption. See Clang's [getNewAlign()](https://github.com/llvm/llvm-project/blob/06499f3672afc371b653bf54422c2e80e1e27c90/clang/include/clang/Basic/TargetInfo.h#L753)

nano-malloc: include long double in malloc alignment union

---

newlib/libc/ctype/ctype_table.c
newlib/libc/ctype/iswalnum_l.c
newlib/libc/ctype/iswalpha_l.c
newlib/libc/ctype/iswblank_l.c
newlib/libc/ctype/iswcntrl_l.c
newlib/libc/ctype/iswgraph_l.c
newlib/libc/ctype/iswlower_l.c
newlib/libc/ctype/iswprint_l.c
newlib/libc/ctype/iswpunct_l.c
newlib/libc/ctype/iswspace_l.c
newlib/libc/ctype/iswupper_l.c
newlib/libc/ctype/jp2uc.c
newlib/libc/ctype/local.h
newlib/libc/locale/nl_langinfo.c
test/meson.build
test/test-wctype.c

This is required by the C language. To match glibc, make *all* of the wide ctype functions return false for non-ASCII values in the C locale.
This should resolve the question raised in #917

ctype: In "C" locale, make iswblank return true for only space and tab

---

newlib/libm/machine/riscv/s_sqrt.c

Make sqrt function aliases for correct types if double and long double are the same size, then alias double function to the long double name.
Before this change: building picolibc on RISCV with -Zd -Zf with forcing math-errno that calls sqrtl() function; the application will fail compilation as sqrtl is an undefined symbol in this case.

[riscv/math] Make sqrt function aliases for correct types

---

picocrt/machine/aarch64/crt0.S
picocrt/machine/aarch64/crt0.c

The AArch64 FVP (Fixed Virtual Platform) R models differ from A models in a few ways which affect the crt0 code:
1. They boot up at EL2, instead of EL3, so we need to set the EL2 versions of the 
system registers.
3. It does not implement the full VMSA. Simpler memory management is sufficient.

Add bootcode for AArch64-R FVPs.

---

zephyr/zephyr.cmake

[Zephyr's fork of picolibc](https://github.com/zephyrproject-rtos/picolibc) currently carries a [single patch](https://github.com/zephyrproject-rtos/picolibc/commit/82d62ed1ac55b4e34a12d0390aced2dc9af13fc9) written by @kiethp , which disables LTO from the picolibc build for Zephyr. However, this patch has a flaw in that it hard-codes use of the `-fno-lto` flag which is not necessarily available on legacy versions of GCC, or certain non-GCC compilers.
This PR contains an updated version of the patch that instead uses the `prohibit_lto` CMake target compiler property which is determined by the Zephyr build system in [compiler_flags.cmake](https://github.com/zephyrproject-rtos/zephyr/blob/main/cmake/compiler/gcc/compiler_flags.cmake#L27).
Furthermore, this PR proposes this patch for …

zephyr: Disable LTO when building the library

---

newlib/libc/tinystdio/gets.c
newlib/libc/tinystdio/stdio.h

This function is impossible to use safely.
It has been officially removed from ISO C11 and ISO C++14. It remains available when explicitly using an old ISO C, Unix, or POSIX standard. Also in glibC it's guarded not be exits in C11, C++14 or beyond: https://github.com/lattera/glibc/blob/master/libio/stdio.h

add guard to gets function to not be exist in C11, C++14 or larter.

---

CMakeLists.txt
meson.build
meson_options.txt
newlib/libc/ctype/ctype_.c
newlib/libc/ctype/ctype_.h
newlib/libc/iconv/iconv.c
newlib/libc/iconv/iconv_close.c
newlib/libc/include/ctype.h
newlib/libc/include/sys/_types.h
newlib/libc/include/sys/config.h
newlib/libc/locale/locale_ctype_ptr.c
newlib/libc/locale/locale_ctype_ptr_l.c
newlib/libc/locale/locale_names.c
newlib/libc/locale/locale_private.h
newlib/libc/locale/localedata.c
newlib/libc/locale/newlocale.c
newlib/libc/locale/setlocale.c
newlib/libc/stdlib/local.h
newlib/libc/stdlib/mbtowc_r.c
newlib/libc/stdlib/wctomb_r.c
picolibc.h.in
test/meson.build

Adds ucs-2 and ucs-4 locales so that iconv can support those. Adds error checking for iconv and iconv_close in case applications pass the (iconv_t) -1 along.

Locale and iconv fixes found by glibc test suite

---

newlib/libc/time/gmtime_r.c

days calculation overflows LONG_MIN/LONG_MAX for large 64-bit timestamps (where time_t is 64 bit)

Avoid integer overflow with large dates in gmtime_r

---

newlib/libc/include/ctype.h
newlib/libc/uchar/c16rtomb.c
newlib/libc/uchar/c32rtomb.c
newlib/libc/uchar/c8rtomb.c
newlib/libc/uchar/mbrtoc16.c
newlib/libc/uchar/mbrtoc32.c
newlib/libc/uchar/mbrtoc8.c

libstdc++ uses `_ctype_` and the various ctype bitmasks, so we need to make those visible when compiling with C++.
The spec doesn't require that uchar static mbstate_t values be thread local, and that wastes memory for applications using them as intended.

ctype: Fixup for C++ compatibility, remove _Thread from uchar statics

---

test/test-except.c

`.inst` ensures that endianness is taken care of.

Make test-except work in AArch32 big endian

---

newlib/libc/stdlib/mbtowc.c

mbtowc() function can only return the number of bytes consumed to convert a valid multibyte character or 0 if the input points to a null character or -1 if the input points to an invalid multibyte sequence.
before this change, if _MBTOWC call is __ascii_mbtowc() and n = 0 it will return -2 in retval and the mbtowc return the retval as it is which is non-standard it should return -1 if the conversion is invalid which is the case with n = 0

stdlib: mbtowc() function can't return -2

---

newlib/libc/locale/locale_private.h

According to ISO/IEC 9899:1999 7.23.3.5 The strftime function
'%X is replaced by the locale's appropriate time representation' (not date representation like %x)
It also states in the same section 7.23.3.5 part 7: 'In the "C" locale %X is equivalent to %T'

locale/time: Fix for strftime() function with '%X' format

---

newlib/libc/picolib/machine/arm/CMakeLists.txt
newlib/libc/picolib/machine/arm/meson.build
newlib/libc/picolib/machine/arm/read_tp.S
newlib/libc/picolib/machine/arm/set_tls.c
newlib/libc/picolib/machine/arm/tls.c

Apps using the standard crt0 will write this value, but if they don't use any thread-local variables, they won't need the reading function.

picolib/arm: Split 'tls' variable out of read_tp asm code

---

newlib/libc/stdlib/wctomb_r.c
newlib/libc/uchar/c16rtomb.c
test/meson.build
test/test-uchar.c
test/test-wctomb.c

When wchar_t is 2 bytes, check stream of values into wcrtomb more carefully. Don't emit any data until we have checked both surrogates so that applications don't receive partial data for potentially incorrect input. Don't allow a surrogate pair to be split by non-surrogate values. Remove redundant low surrogate handling code.
Add some tests to validate the code.
This replaces the third patch in #951

stdlib: Handle surrogate errors better in wcrtomb

---

newlib/libc/uchar/c32rtomb.c
newlib/libc/uchar/mbrtoc32.c

Fixes in mb/wc conversion functions:
1- mbrtoc32() should ignore parameter pc32 if s is a null pointer
2- c32rtomb() Explicitly handle s = NULL in c32rtomb() function
3- __utf8_wctomb() should store nothing if the conversion is inclomplete yet.

uchar: Fixes in mb/wc conversion functions

---

newlib/libm/machine/riscv/s_lrint.c

Make `lrint` function aliases for correct types if `double` and `long double` are the same size, then alias double function to the long double name.
Before this change: building picolibc on RISCV with `-Zd` or `-Zdinx`  that calls `lrintl()` function; the application will fail compilation as `lrintl` is an undefined symbol in this case.
inclusion of `math_config.h` is added in order to get `_MATH_ALIAS_j_d` symbol definition.
Similar to https://github.com/picolibc/picolibc/pull/926

[riscv/math] Make `lrint` function aliases for correct types

---

picolibc.ld.in

Sorted `.text.*` subsections were added to GNU `ld`'s default linker script & supporting code, around 2019 (https://sourceware.org/pipermail/binutils/2019-September/108181.html). They were introduced to aid link-time optimisation, & may also have other uses.

Have linker script spot .text.sorted.* sections, & sort them

---

newlib/libc/stdlib/CMakeLists.txt
newlib/libc/stdlib/meson.build

The file `ignore_handler_s.c` was not included in the `stdlib` CMakeLists.txt and meson.build, causing it to be omitted from the build. This PR adds it to both build systems to ensure it is compiled and linked correctly.

stdlib: Add ignore_handler_s.c to CMakeLists.txt and meson.build

---

newlib/libc/include/sys/_types.h

To guarantee that `off_t >= size_t` 
As required to build  fmemopen.c line [117](https://github.com/picolibc/picolibc/blame/d44fa19886bad821f6004583c75bfc202cd4b156/newlib/libc/tinystdio/fmemopen.c#L117C14-L117C14):
` _Static_assert(sizeof(off_t) >= sizeof(size_t), "must avoid truncation");` 
Also to comply with the assumption in [your disccusions](https://github.com/picolibc/picolibc/pull/634#discussion_r1376668351)
The problem is in 64-bit systems `long` type can be configured to be 4-bytes and `long long` to be 8-bytes then `off_t` and `size_t w` will be mapped as follows:
- `size_t` -> `__SIZE_TYPE__` -> `long long` -> **8**-bytes.  Note that `__SIZE_TYPE__` is compiler predefined macro
- `off_t`  -> `long` -> **4**-bytes
which results in library failing to build in such environment.

Promote `off_t` type when `long->4-bytes` and `size_t->8-bytes`

---

newlib/libc/stdlib/mbtowc.c

Enhancement over this PR: https://github.com/picolibc/picolibc/pull/947 it missed setting the retval to -1 if the input points to an invalid multibyte sequence.

stdlib: mbtowc() should return -1 with invalid multibyte sequence

---

newlib/libc/machine/arc/memset-bs.S
newlib/libc/machine/arc/strncpy.S
test/meson.build
test/test-strncpy.c

The memset code has a special entry point used to clear space beyond the destination in strncpy. To make it work, the destination is passed in r3 instead of r0 (as r0 must hold the final return value).
However, the code to clear the unaligned end of the string was mistakenly computing the end address using r0 instead of r3. If the number of bytes to erase was smaller than the copied string, that would end up smashing bytes in the middle of the result instead of clearing bytes at the end.

machine/arc: strncpy fails as __strncpy_bzero passes target addr in r3, not r0

---

picocrt/machine/arm/crt0.c

This CP15 register, which controls the exception vector table base address, is part of the Security Extensions, which are not available in Armv7-R. So the MCR instruction which writes to them will provoke an UNDEF exception on an Armv7-R CPU.
This MCR instruction was already conditionally compiled: if you're compiling crt0.c for a platform without it, you just have to make sure your ld script puts the exception vectors in the default place. This patch tightens the existing condition to exclude Armv7-R.

AArch32 crt0: don't write to VBAR on Armv7-R systems.

---

meson.build

The LLVM libcxx library uses `_NEWLIB_VERSION` across its codebase. The recent renaming broke the build of libcxx because of this.
This patch reintroduces the macro definition for compatibility with LLVM libcxx.

Define _NEWLIB_VERSION for the use of picolibc with LLVM libcxx

---

doc/locking.md
newlib/libc/machine/x86/machine/fenv.h
newlib/libc/picolib/dso_handle.c
newlib/libc/stdlib/environ.c
newlib/libc/xdr/xdr.c
newlib/libm/ld/ld128/e_expl.c
newlib/libm/ld/ld128/e_tgammal.c
newlib/libm/ld/ld128/s_exp2l.c
newlib/libm/ld/ld80/e_expl.c
newlib/libm/ld/ld80/e_log10l.c
newlib/libm/ld/ld80/e_log2l.c
newlib/libm/ld/ld80/e_logl.c
newlib/libm/ld/ld80/e_tgammal.c
newlib/libm/ld/ld80/s_exp2l.c
newlib/libm/ld/ld80/s_log1pl.c
newlib/libm/machine/x86/fenv.c
scripts/do-native-configure
test/tls.c

A bunch of data (especially in the long-double code) was missing `const` annotation. Fix that, along with updating the locking document.

Clean up constant data marked read-write

---

meson.build

This fixes a bug in f440a10467ef713d3d78bc31413726755986df42 which I triggered when trying to add TLS support for x86, due to differences in stack guard handling on different types of x86 host platforms.

Bug fix: ensure library built with given 'stack-protector-guard' setting

---

newlib/libc/include/stdlib.h
newlib/libc/stdlib/nano-memalign.c

We need to provide a way for aligned_alloc to be built even using an older compiler. Add it to the GNU_VISIBLE class so that stdlib.h will declare it, even for pre-C11 compilers.

stdlib: Allow aligned_alloc to build in c99 mode too

---

newlib/libc/include/stdlib.h
newlib/libc/include/sys/cdefs.h

GCC supports two forms of the deprecated attribute, one with no argument that prints a generic message and another with a string argument that is displayed as part of the warning. Zephyr uses only the argument-free version and calls that __deprecated.
To avoid conflicting with that, replicate that behavior in picolibc and then create another macro, __deprecated_m(s), which takes the message and can be used in the one place in picolibc headers which expose a deprecated function (mktemp).

cdefs: Create separate __deprecated_m that takes a message

---

newlib/libc/ctype/ctype_.h
newlib/libc/ctype/isalnum.c
newlib/libc/ctype/isalnum_l.c
newlib/libc/ctype/isalpha.c
newlib/libc/ctype/isalpha_l.c
newlib/libc/ctype/isblank.c
newlib/libc/ctype/isblank_l.c
newlib/libc/ctype/iscntrl.c
newlib/libc/ctype/iscntrl_l.c
newlib/libc/ctype/isdigit.c
newlib/libc/ctype/isdigit_l.c
newlib/libc/ctype/isgraph.c
newlib/libc/ctype/isgraph_l.c
newlib/libc/ctype/islower.c
newlib/libc/ctype/islower_l.c
newlib/libc/ctype/isprint.c
newlib/libc/ctype/isprint_l.c
newlib/libc/ctype/ispunct.c
newlib/libc/ctype/ispunct_l.c
newlib/libc/ctype/isspace.c
newlib/libc/ctype/isspace_l.c
newlib/libc/ctype/isupper.c
newlib/libc/ctype/isupper_l.c
newlib/libc/ctype/isxdigit.c
newlib/libc/ctype/isxdigit_l.c
newlib/libc/include/ctype.h

Using _U et al makes these symbols far more likely to collide with application usage. Avoid that by making the names all start with __CTYPE along with a longer description of their function.
To avoid breaking libstdc++, expose the old symbols for C++. As that didn't used to include the tab bit, don't include it now.

ctype: Rename bit definitions to avoid application symbols

---

newlib/libc/stdlib/random.c

Closes #988
I checked newlib's source code and found that they use `unsigned long long`, which is what I changed the previous `long long` to here.

stdlib: use unsigned arithmetic in rand() to fix overflow

---

meson.build
newlib/libc/machine/x86/machine/_ssp_tls.h
newlib/libc/machine/x86/machine/_tls.h
newlib/libc/picolib/machine/x86/CMakeLists.txt
newlib/libc/picolib/machine/x86/meson.build
newlib/libc/picolib/machine/x86/tcb-32.S
newlib/libc/picolib/machine/x86/tcb-64.S
newlib/libc/picolib/machine/x86/tcb.S
newlib/libc/picolib/machine/x86/tls.c
picocrt/machine/x86/crt0-32.S
picolibc.ld.in

On the x86, the precise procedure for setting the current TCB pointer -- the `%gs` segment base (for i386) or the `%fs` base (for x86-64) -- is unfortunately OS-specific, since it generally involves privileged operations.
The current proposed arrangement is to have an OS-indepedent `_set_tls()` routine calculate the TCB address from the TLS base -- by adding the needed offset -- and then simply hand over to a lower layer `__set_tcb()` routine to actually set the TCB pointer.
(The `__set_tcb()` interface follows that of OpenBSD: see https://man.openbsd.org/__get_tcb.2 .)
The linker script was also modified to allocate space for the thread control block, which on the x86 appears _after_ the TLS variables (https://akkadia.org/drepper/tls.pdf).

semihost/x86: add TLS support for semihosting Intel i386 and x86-64

---

newlib/libc/ubsan/CMakeLists.txt
newlib/libc/ubsan/meson.build
newlib/libc/ubsan/ubsan.h
newlib/libc/ubsan/ubsan_handle_vla_bound_not_positive.c

Another missing ubsan handler from gcc.

ubsan: Add __ubsan_handle_vla_bound_not_positive

---

newlib/libc/stdio/nano-vfprintf.c
newlib/libc/stdio/nano-vfprintf_float.c
newlib/libc/stdio/nano-vfscanf.c
newlib/libc/stdio/nano-vfscanf_float.c
newlib/libc/stdio/stdio.h

Remove 'struct _reent' dregs. Add __nothrow as needed to stdio.h. Clean up some simple compiler warnings about undefined behavior.
There are many gaps in standards conformance with this; making it pass the test suite would be a significant effort. But, at least it builds again.

stdio: Make legacy nano printf code at least compile

---

CMakeLists.txt
newlib/libc/misc/init.c

When __INIT_FINI_FUNCS is set, use the correct symbol for the end of the init funcs.
Change cmake default for __INIT_FINI_FUNCS to match meson, which is to disable them.
Closes: #1012

Fix __INIT_FINI_FUNCS usage and cmake default

---

meson.build
picolibc.specs.in

For targets which need _ prepended to global symbols, add _ to the general symbols (vfprintf/vfscanf) as well as the specific symbols (__i_vfprintf/__i_vfscanf).
Add prefixes to --printf and --scanf compiler command line options.

picolibc.specs: Make sure printf/scanf symbols get _ prepended as needed

---

newlib/libc/machine/arm/arm_asm.h
newlib/libc/machine/arm/memchr.S
newlib/libc/machine/arm/memcpy-armv7m.S
newlib/libc/machine/arm/memset-thumb.S
newlib/libc/machine/arm/memset-thumb2.S
newlib/libc/machine/arm/strcmp-arm-tiny.S
newlib/libc/machine/arm/strcmp-armv7.S
newlib/libc/machine/arm/strcmp-armv7m.S
newlib/libc/machine/arm/strcpy.S
newlib/libc/machine/arm/strlen-armv7.S
newlib/libc/machine/arm/strlen-thumb2-Os.S

A bunch of arm string code was generating exception table information even though they are all leaf functions and raise no exceptions. Disable these by creating empty macros in case they need to be re-enable in the future.
Fixes issue identified in #1024

machine/arm: Disable exception tables in ARM string asm code

---

meson.build

The checks have become dead after a1548f14.

Remove dead checks for builtins support

---

newlib/libc/include/inttypes.h
newlib/libc/include/stdint.h

The values computed in _intsup.h are only used in inttypes.h, so move the include of that file from stdint.h to inttypes.h. This fixes gcc installations which override our stdint.h with the gcc version that doesn't include this file.

include: Move use of _intsup.h from stdint.h to inttypes.h

---

meson.build
newlib/libm/machine/powerpc/meson.build
test/meson.build
test/test-flockfile.c

When performing meson compiler tests that use linking, we need to pass along an alias for '_start' so that linking doesn't  rely upon any startup code. Share the code which detects which command line form aliases require to do this.
Stick this argument, along with any runtime library (libgcc or libclang_rt.builtins) in the 'link_test_args' variable for use by other tests.

meson: Rework how compiler link tests are done

---

newlib/libc/include/machine/ieeefp.h
newlib/libc/include/sys/config.h
newlib/libc/machine/loongarch/machine/fenv-fp.h
newlib/libm/common/math_config.h
newlib/libm/ld/math_ld.h

Don't expose the symbols in this public file to every library user. Move all of the float symbol settings to ieeefp.h

include/sys: Remove <float.h> from config.h

---

CMakeLists.txt
meson.build
meson_options.txt
newlib/libc/stdlib/CMakeLists.txt
newlib/libc/stdlib/meson.build
zephyr/zephyr.cmake

This new option (enable-malloc in meson, ENABLE_MALLOC in cmake) controls whether the library includes an implementation of the malloc functions:
* malloc
* calloc
* aligned_alloc
* memalign
* posix_memalign
* pvalloc
* valloc
* realloc
* free
* cfree
* malloc_usable_size
* getpagesize
* mallinfo
* malloc_stats
The option is enabled by default, although the Zephyr configuration disables it as Zephyr always uses their own internal malloc implementation.

stdlib: Add enable-malloc/ENABLE_MALLOC config option

---

meson.build

%s asks gcc to search for the generated filename, but if we compute the full path that will generate the wrong result when using getenv. We don't need gcc to search anyways; we're computing the complete path name.

Remove '%s' from startfile spec when using complete path

---

picocrt/machine/riscv/crt0.c
scripts/cross-coreboot-arm-eabi.txt
scripts/cross-riscv64-zephyr-elf.txt
scripts/do-coreboot-arm-eabi-configure
scripts/run-arm
scripts/run-riscv

There were a couple non-large model addressing operations in crt0, and the vector unit wasn't getting enabled.
The run-riscv script wasn't enabling all required extensions; parse the readelf output and map those to qemu command line options.

Handle riscv large model and vector extension. Fix riscv extension stuff for qemu

---

newlib/libc/machine/arm/arm_asm.h
newlib/libc/machine/arm/memcpy-armv7a.S
newlib/libc/machine/arm/memcpy-armv7m.S
newlib/libc/picolib/machine/arm/interrupt.c
picocrt/machine/arm/crt0.c

- Make Armv7-A memcpy work in Thumb state
The implementation of Armv7-A's `memcpy` requires Arm state, therefore callers from Thumb state must perform an interworking call by the use of `BLX`.
Before this patch, the alias declaration for `__aeabi_memcpy(4|8)?` used a macro (`ASM_ALIAS`) that, when targeting Thumb, used the directive `.thumb_set`.  This directive, in this specific case, wrongly marked the alias as a Thumb entry point.
This patch defines a new macro to define an alias unconditionally for the Arm state, and uses this new macro to define the aliases to `memcpy`.
- AArch32 A-profile using Thumb state must stay at it on exception entry
On exception entry, the architecture may switch ISA depending on the TE bit of the SCTLR register.
Before this patch, the startup code was …

Fixes to make AArch32 A-profile work better in Thumb state

---

newlib/libm/common/exp.c
newlib/libm/common/exp2.c
newlib/libm/common/log.c
newlib/libm/common/log2.c
newlib/libm/common/pow.c
newlib/libm/common/sf_pow.c

Use preprocessor directives instead of using the macro in if statements.

libm: use the WANT_ROUNDING macro in #if directives

---

newlib/libc/include/math.h

This PR removes the unguarded declarations of `isinf(double)` and `isnan(double)` that were introduced in [commit 407b3d8](https://github.com/picolibc/picolibc/commit/407b3d8e8b407a1eb8e2a630abd5bac2a3fcc6a3), which conflict with C++11 and later.
These functions were already added (correctly) under C++ version guards in [commit 722e363](https://github.com/picolibc/picolibc/commit/722e363c4de410e67f24d0da3129c446074716bc).
The duplicate, unguarded declarations cause ambiguity when including `<math.h>` or `<cmath>` in C++11+, since those functions are also provided as built-ins.
This PR keeps only the guarded declarations to maintain compatibility with both C and modern C++.
Closes:#[163](https://github.com/picolibc/picolibc/issues/1063)

Remove duplicate unguarded declarations of `isinf` and `isnan` in `<math.h>`

---

newlib/libc/machine/riscv/CMakeLists.txt
newlib/libc/machine/riscv/memmove.S
newlib/libc/machine/riscv/memmove.c
newlib/libc/machine/riscv/meson.build
newlib/libc/machine/riscv/rv_memmove.h

For RISC-V, it is possible to have several optimized implementations of library routines depending on which hardware extensions are enabled and the current mechanism to choose the appropriate implementation will quickly become messy when dealing with many implementations.
With this change, the idea is 'newlib/libc/machine/riscv/memmove.c' will override the generic 'newlib/libc/string/memmove.c' through the 'srcs_machine' scheme and conditions in 'newlib/libc/machine/riscv/memmove.c' will decide which implementation gets compiled and used for a given scenario.
I think this mechanism is simple and scalable.
The remaining RISC-V specific library implementations are either only assembly or only C. Probably we don't need to change those at this moment.

machine/riscv: Refactor machine specific memmove overriding mechanism

---

newlib/libc/include/setjmp.h
newlib/libc/include/sys/cdefs.h

This lets the compiler know how setjmp works and makes sure all register contents are dead across the call.

cdefs: Add __returns_twice and use with setjmp
