.github/Dockerfile

Dockerfile: fix typo

---

newlib/libc/include/time.h
newlib/libc/time/mktime.c

This is a first draft for timegm() without documentation, tests or any other code clean-ups or optimisations present in the older patch, just to discuss the basic code changes and the way forwards.

Add timegm

---

newlib/libc/stdlib/meson.build
newlib/libc/stdlib/pico-cxa-atexit.c
newlib/libc/stdlib/pico-onexit.c
newlib/libc/stdlib/pico-onexit.h

This is required for C++ applications.

stdlib: Add pico version of __cxa_atexit

---

COPYING.picolibc
newlib/libc/tinystdio/meson.build
newlib/libc/tinystdio/stdio.h
newlib/libc/tinystdio/vsscanf.c
picolibc.specs.in

Add vsscanf

---

.github/do-build
.github/do-test
.github/workflows/minsize.yml
.github/workflows/release.yml
meson.build
newlib/libc/stdio/vfprintf.c
newlib/libc/stdio/vfwprintf.c
newlib/libc/stdlib/ldtoa.c
scripts/do-configure
scripts/do-rv32imac-configure
test/printf_scanf.c

Also removes an unused variable in ldtoa

Fix ldtoa typo, test ldtoa

---

.github/Dockerfile
.github/workflows/minsize.yml
.github/workflows/release.yml

Hope this one works.  This is related to #189.

Docker Speed Enhancement

---

newlib/libc/stdio/fwrite.c
newlib/libc/tinystdio/fputs.c
newlib/libc/tinystdio/fwrite.c
newlib/libc/tinystdio/posixio.c
newlib/libc/tinystdio/puts.c
semihost/sys_putc.c
test/meson.build
test/test-put.c

Make fwrite, fputs and puts deal with 'put' hook returning positive values.
Change sample put hooks to return (unsigned char) c to test above change.
Add tests for these functions.

tinystdio fixes

---

newlib/libc/tinystdio/atod_ryu.c
newlib/libc/tinystdio/atof_ryu.c
newlib/libc/tinystdio/ryu/d2s_intrinsics.h
newlib/libc/tinystdio/ryu_divpow2.c
newlib/libc/tinystdio/ryu_table.c
newlib/libc/tinystdio/ryu_umul128.c

This brings the ryu code in tinystdio up to
commit 150d0c87830756d34e76c42f7f33f811d89903a8

tinystdio: Pull in changes to the ryu code

---

.github/do-many
.github/workflows/linux.yml
.github/workflows/targets-arm
.github/workflows/targets-misc
.github/workflows/targets-ppc
.github/workflows/targets-riscv

Instead of rebuilding the container for every run, chain the tests
together to share the cost of building it.

.github: Run multiple tests in each container

---

meson.build

This is just to test the mesonupdate branch applied to main

Rebase Meson update branch to main

---

newlib/libc/include/arpa/inet.h
newlib/libc/include/arpa/meson.build
newlib/libc/include/machine/endian.h
newlib/libc/include/rpc/meson.build
newlib/libc/include/sys/cdefs.h
newlib/libc/include/sys/meson.build
newlib/libc/string/local.h
newlib/libc/tinystdio/filestrput.c
newlib/libc/tinystdio/fputc.c
newlib/libc/tinystdio/ryu/d2s_intrinsics.h
newlib/libc/tinystdio/ryu/f2s_intrinsics.h
newlib/libc/tinystdio/snprintfd.c
newlib/libc/tinystdio/snprintff.c
newlib/libc/tinystdio/sprintfd.c
newlib/libc/tinystdio/sprintff.c
newlib/libc/tinystdio/stdio.h
newlib/libc/tinystdio/vfprintf.c
newlib/libm/math/s_jn.c
semihost/machine/i386/e9_io.c

Here's a collection of picolibc fixes found using the Zephyr test suite.

Zephyr fixes

---

.github/packages.txt
.github/workflows/linux.yml
.github/workflows/make-workflow
.github/workflows/targets-mips
newlib/libc/machine/mips/machine/fenv-fp.h
newlib/libc/machine/mips/machine/fenv-softfloat.h
newlib/libc/machine/mips/machine/meson.build
newlib/libc/machine/mips/meson.build
newlib/libc/machine/mips/strncpy.c
newlib/libc/machine/mips/sys/meson.build
newlib/libc/stdlib/strtod.c
newlib/libc/tinystdio/strtod.c
newlib/libc/tinystdio/strtod_l.c
newlib/libm/common/fabsl.c
newlib/libm/complex/cabsl.c
newlib/libm/machine/mips/fenv.c
newlib/libm/machine/mips/meson.build
newlib/libm/math/s_hypot.c
scripts/cross-mips-linux-gnu.txt
scripts/cross-mipsel-linux-gnu.txt
scripts/do-mips-configure
scripts/do-mipsel-configure

Add meson build files along with a few fixups to make Picolibc support MIPS targets.

Add MIPS support

---

.github/workflows/linux.yml
.github/workflows/variants
newlib/libc/stdlib/__atexit.c

Looks like there's a bug here, so let's test it and make sure it fails before
adding a fix.

.github: Test non-picoexit configuration

---

newlib/libc/machine/x86/meson.build
newlib/libm/machine/x86/meson.build
semihost/machine/x86/meson.build

Instead of doing another merge, rebase patches from main for x86 on top of the esp32 merge.

Rebase x86 fixes on top of esp32 merge

---

.github/do-zephyr
.github/extra-files.txt
.github/workflows/linux.yml
.github/workflows/make-workflow
.github/workflows/targets-xtensa
scripts/cross-xtensa-espressif_esp32_zephyr-elf.txt
scripts/cross-xtensa-espressif_esp32s2_zephyr-elf.txt
scripts/cross-xtensa-intel_apl_adsp_zephyr-elf.txt
scripts/cross-xtensa-intel_bdw_adsp_zephyr-elf.txt
scripts/cross-xtensa-intel_byt_adsp_zephyr-elf.txt
scripts/cross-xtensa-intel_s1000_zephyr-elf.txt
scripts/cross-xtensa-nxp_imx8m_adsp_zephyr-elf.txt
scripts/cross-xtensa-nxp_imx_adsp_zephyr-elf.txt
scripts/cross-xtensa-sample_controller_zephyr-elf.txt
scripts/do-xtensa-espressif_esp32-configure
scripts/do-xtensa-espressif_esp32s2-configure
scripts/do-xtensa-intel_apl_adsp-configure
scripts/do-xtensa-intel_bdw_adsp-configure
scripts/do-xtensa-intel_byt_adsp-configure
scripts/do-xtensa-intel_s1000-configure
scripts/do-xtensa-nxp_imx8m_adsp-configure
scripts/do-xtensa-nxp_imx_adsp-configure
scripts/do-xtensa-sample_controller-configure

Zephyr provides a number of toolchains for xtensa targets. Use those to build picolibc during CI.

.github: Build xtensa libs using zephyr toolchains

---

newlib/libc/picolib/machine/xtensa/CMakeLists.txt
newlib/libc/picolib/machine/xtensa/meson.build
newlib/libc/picolib/machine/xtensa/tls.c

xtensa: Add _set_tls helper

---

CMakeLists.txt
README.md
doc/releasing.md
meson.build

Version 1.8

---

doc/locking.md

Fix a typo in locking.md

---

newlib/libc/include/sys/lock.h
newlib/libc/misc/lock.c
newlib/libc/search/hash_bigkey.c
test/lock-valid.c

Remove the try_acquire APIs plus a couple of test fixups.

Lock cleanups

---

meson.build
meson_options.txt
newlib/libc/misc/meson.build
newlib/libc/misc/ubsan.c
scripts/do-native-configure
test/meson.build
test/test-ubsan.c

This adds meson configuration options and a test.

Support -fsanitize=bounds

---

test/math_errhandling.c
test/math_errhandling_tests.c

Targets with mixed hard/soft float implementations generally don't support exceptions for types implemented in software. Because we want to signal that support to applications in fenv.h, we need to know that at compile time, not runtime. To validate that those settings are correct, add a test to compare the compile-time values with runtime.
See #500

test: Validate exception configuration for various float types

---

.github/Dockerfile-zephyr
.github/do-zephyr
.github/zephyr
.github/zephyr-files.txt
.github/zephyr-setup
picocrt/machine/arc/CMakeLists.txt
picocrt/machine/arc/crt0.c
picocrt/machine/arc/meson.build
scripts/cross-arc-zephyr-elf.txt
scripts/run-arc
semihost/machine/arc/CMakeLists.txt
semihost/machine/arc/arc_close.c
semihost/machine/arc/arc_exit.c
semihost/machine/arc/arc_fstat.c
semihost/machine/arc/arc_lseek.c
semihost/machine/arc/arc_open.c
semihost/machine/arc/arc_read.c
semihost/machine/arc/arc_semihost.h
semihost/machine/arc/arc_stat.c
semihost/machine/arc/arc_stub.c
semihost/machine/arc/arc_unlink.c
semihost/machine/arc/arc_write.c
semihost/machine/arc/meson.build

Build enough support in picocrt and semihost to run tests

Test arc architecture under qemu

---

.github/do-arm
.github/workflows/macos.yml

No reason to spin up three instances when the tests all run so fast.

.github: Merge all of the macos tests into a single pass

---

picocrt/machine/msp430/crt0.c
picocrt/machine/msp430/meson.build
test/printf-tests.c

This is a copy of commit f8200016bf.
This is enough to make the CPU start
and make the test code execute.

picocrt: add msp430 support

---

COPYING.picolibc
README.md
meson.build

Proposed release 1.8.4. This will occasionally get rebased until the release is ready.

Branch 1.8.4

---

.github/linux-files.txt

This seems to avoid the timing bug when reading from stdin

.github: Update qemu-system-arm

---

.github/do-zephyr
.github/zephyr-files.txt
README.md
newlib/libc/machine/aarch64/CMakeLists.txt
newlib/libc/machine/aarch64/meson.build
newlib/libc/machine/sparc/setjmp.S
newlib/libc/picolib/machine/sparc/CMakeLists.txt
newlib/libc/picolib/machine/sparc/interrupt.S
newlib/libc/picolib/machine/sparc/meson.build
newlib/libc/picolib/machine/sparc/tls.c
picocrt/machine/sparc/crt0.c
picocrt/machine/sparc/meson.build
picolibc.ld.in
scripts/cross-sparc-zephyr-elf.txt
scripts/do-arc-configure
scripts/do-arc64-configure
scripts/do-arm-configure
scripts/do-m68k-configure
scripts/do-m68k-unknown-elf-configure
scripts/do-nios2-configure
scripts/do-riscv-configure
scripts/do-sparc-zephyr-configure
scripts/run-sparc
semihost/machine/sparc/meson.build
semihost/machine/sparc/sparc-semihost.h
semihost/machine/sparc/sparc_exit.c
semihost/machine/sparc/sparc_iob.c
semihost/machine/sparc/sparc_stub.c

Use the Zephyr toolchain to test the sparc code.

Test sparc

---

newlib/libc/tinystdio/ultoa_invert.c
test/meson.build
test/test-long-long.c

Share a single implementation between 32 and 64 bit values. Add a bunch of comments explaining how the math works.
Add some more testing.

tinystdio: Clean up ultoa_invert.c a bit

---

meson.build
newlib/libc/tinystdio/vfprintf.c
scripts/cross-clang-thumbv6m-none-eabi.txt
test/lock-valid.c
test/meson.build
test/test-fopen.c
test/test-fread-fwrite.c

Use different sizes, seek between some operations. Use ungetc sometimes.

test: Add test for fread and fwrite

---

.github/workflows/linux.yml
.github/workflows/variants
.github/workflows/zephyr.yml
doc/build.md
meson.build
meson_options.txt
newlib/libc/tinystdio/bufio.c
newlib/libc/tinystdio/fputc.c
newlib/libc/tinystdio/fputs.c
newlib/libc/tinystdio/fread.c
newlib/libc/tinystdio/fwrite.c
newlib/libc/tinystdio/puts.c
newlib/libc/tinystdio/stdio-bufio.h
newlib/libc/tinystdio/ungetc.c
newlib/libc/tinystdio/vfprintf.c
scripts/cross-clang-thumbv6m-none-eabi.txt
test/lock-valid.c
test/meson.build
test/test-fopen.c
test/test-fread-fwrite.c

Check if the underlying FILE is bufio and do I/O with direct read/write instead of using getc/putc hooks

tinystdio: Optimize fread/fwrite on bufio files

---

newlib/libc/machine/m68k/machine/fenv-fp.h
newlib/libc/machine/mips/machine/fenv-fp.h
newlib/libc/machine/riscv/machine/fenv-fp.h
newlib/libm/machine/x86/fenv.c
test/math-funcs.c

Add all of the functions to the math-funcs test, which just calls them all.

Make sure all of the fenv functions exist

---

newlib/libc/machine/aarch64/machine/fenv-fp.h
newlib/libc/machine/m68k/machine/fenv-fp.h
newlib/libc/machine/riscv/machine/fenv-fp.h
test/fenv.c
test/meson.build

Check the value before returning an error. Also add some tests to make sure other archs also work right

riscv: feenableexcept(0)/fedisableexcept(0) should work 

---

picocrt/machine/arm/crt0.c
scripts/cross-arm-none-eabi.txt
scripts/do-arm-configure

There was a compiler bug which prevented this from landing until the debian testing compiler was patched. With that finished, this should be ready.

Enable PACBTI for arm v8.1m

---

picocrt/machine/arm/crt0.c

Users optimizing for size might well want to leave printf out of their link completely, if their I/O needs are not complicated. But if they're using the fault reporting functions in arm/crt0.c, then they get printf pulled in anyway by `arm_fault()`.
This patch reworks `arm_fault()` to use only puts/fputs, and do its hex number formatting by hand in as little code as possible.
(I considered using `utoa` for the number formatting, but it has the wrong feature set: here we don't need its support for arbitrary number bases, and on the other hand, we do want fixed-width hex numbers instead of minimal-width.)

arm/crt0.c: Print register dumps without using printf

---

newlib/libc/include/fenv.h
newlib/libc/include/machine/fenv-softfloat.h
newlib/libc/include/sys/fenv.h
newlib/libc/machine/arm/machine/fenv-fp.h
newlib/libc/machine/arm/sys/fenv.h
newlib/libc/machine/m68k/machine/fenv-fp.h
newlib/libc/machine/m68k/sys/fenv.h
newlib/libc/machine/mips/sys/fenv.h
newlib/libc/machine/riscv/machine/fenv-fp.h
newlib/libc/machine/riscv/sys/fenv.h
newlib/libc/machine/sh/machine/fenv-fp.h
newlib/libc/machine/sh/sys/fenv.h
newlib/libc/machine/sparc/sys/fenv.h
newlib/libc/machine/x86/sys/fenv.h
newlib/libc/machine/xtensa/machine/fenv-fp.h
newlib/libc/machine/xtensa/sys/fenv.h
test/rounding-mode.c

This is a rebase and extension of pr #709 adding the same fix for ARM and then adding a test to make sure it all works.

Abdal fix fesetround

---

newlib/libc/search/qsort.c

This should improve performance for 64-bit architectures since we now copy 64 bits at a type instead of 32 and is in fact required for CHERI.
This change was pulled in from CheriBSD: For CHERI, if the array contains pointers we have to swap pointer-sized elements at a time since partial writes of a CHERI capability invalidate the validity bits. This change could have also replaced `long` with `intptr_t`, but having both cases ensures that if we can't swap a pointer-size element, we use int instead to avoid falling back fall back to int to avoid using the byte copy loop for smaller elements.
Should have no code generation difference for existing 32-bit architectures since the compiler can elide the unreachable branch.

qsort: allow swapping intptr_t-sized elements

---

meson.build

meson: fix specs_prefix_format calculation

---

newlib/libc/include/stdlib.h
newlib/libc/stdlib/ignore_handler_s.c

Adding `ignore_handler_s` function according to C11 standard

Adding ignore_handler_s function

---

newlib/libc/errno/errno.c
newlib/libc/machine/arc/strchr-stub.c
scripts/do-arc-configure
scripts/run-arc
test/test-long-long.c

There are three asm versions of strchr, check for all of them before falling back to the C version.

machine/arc: Check for all strchr asm versions in strchr-stub.c

---

doc/build.md
doc/os.md
doc/printf.md
doc/testing.md
doc/tls.md

Use markdown code blocks for documents
Add code block for code in os.c

Use markdown code blocks

---

newlib/meson.build
scripts/duplicate-names

This provides compatibility with builds that use -lnosys
Closes: #876

newlib: Add empty libnosys.a

---

.github/Dockerfile
.github/Dockerfile-zephyr
.github/linux-files.txt
.github/linux-packages.txt
.github/zephyr-files.txt
.github/zephyr-packages.txt

Let's see if this makes building the container more reliable.

.github: Host toolchain bits at github rather than altusmetrum.org

---

.github/do-linux
.github/linux-packages.txt
newlib/libc/machine/or1k/CMakeLists.txt
newlib/libc/machine/or1k/meson.build
picocrt/machine/or1k/crt0.S
picocrt/machine/or1k/crt0.c
picocrt/machine/or1k/meson.build
scripts/cross-or1k-elf.txt
scripts/do-or1k-configure
scripts/run-or1k
semihost/machine/or1k/meson.build
semihost/machine/or1k/or1k_exit.c
semihost/machine/or1k/or1k_iob.c
semihost/machine/or1k/or1k_semihost.h
semihost/machine/or1k/or1k_stub.c

Add picocrt and semihost support for openrisc so we can actually run tests.

Test openriscv support

---

picocrt/machine/arm/crt0.c

Currently in the Arm crt0.c, we set all the banked SPs to the same address. So if we would change to a different mode from the default supervisor (SVC) mode, we would set the SP back to the original value of the SVC SP, and stomp over the existing values.
This patch sets up different addresses for the different modes at the top of the stack, with the main SVC stack defined at the bottom of these, which then grows towards the heap like before.
The stacks are all set to the very small value of 16 bytes. Enough to be able to debug picolibc test startup code, which currently isn't expected to switch mode in normal operation.

picocrt/arm: For non M-class Arm cores set distinct banked SPs

---

COPYING.picolibc
doc/releasing.md
newlib/libc/include/sys/syslimits.h
scripts/cross-clang-cortex-r82.txt
scripts/cross-clang-riscv64-zephyr-elf.txt
scripts/cross-clang-rv32imafc.txt
scripts/cross-clang-thumb-none-eabi.txt
scripts/cross-clang-thumbv6m-none-eabi.txt
scripts/cross-clang-thumbv7-a-none-eabi.txt
scripts/cross-clang-thumbv7e+dp-none-eabi.txt
scripts/cross-clang-thumbv7e+fp-none-eabi.txt
scripts/cross-clang-thumbv7m-none-eabi.txt
scripts/do-arm-tk

A few doc updates to track release process, then an update for limits.h found while integrating 1.8.9 into Zephyr.

Updates found during 1.8.9 integration

---

.github/do-cmake-linux
.github/do-cmake-test
COPYING.picolibc
cmake/TC-clang-thumbv6m.cmake
cmake/TC-clang-thumbv7m.cmake
cmake/TC-rx.cmake
cmake/TC-rx.ld
cmake/TC-thumbv7m.cmake
newlib/libc/machine/rx/CMakeLists.txt
newlib/libc/picolib/machine/rx/CMakeLists.txt
picocrt/machine/x86/CMakeLists.txt
scripts/do-cmake-rx-configure
semihost/machine/rx/CMakeLists.txt
test/CMakeLists.txt

Add cmake support for RX

---

COPYING.picolibc
README.md
newlib/libc/machine/riscv/rv_string.h
newlib/libc/machine/riscv/strlen.c
newlib/libc/tinystdio/freopen.c
test/semihost/meson.build
test/semihost/semihost-flen.c
test/semihost/semihost-istty.c
test/semihost/semihost-open.c
test/semihost/semihost-read.c
test/semihost/semihost-remove.c
test/semihost/semihost-rename.c
test/semihost/semihost-seek.c
test/semihost/semihost-write.c

test/semihost: use unique filenames for each test
machine/riscv: Support older GCC versions without riscv_bitmanip.h

A couple of minor fixes

---

COPYING.picolibc
newlib/libc/ubsan/CMakeLists.txt
newlib/libc/ubsan/meson.build
newlib/libc/ubsan/ubsan.h
newlib/libc/ubsan/ubsan_cfi_type_check_to_string.c
newlib/libc/ubsan/ubsan_handle_cfi_bad_type.c
newlib/libc/ubsan/ubsan_handle_cfi_check_fail.c
newlib/libc/ubsan/ubsan_handle_dynamic_type_cache_miss.c

One missing handler for GCC and three for clang.

ubsan: Add some missing handlers

---

newlib/libm/common/fdlibm.h

Thanks to Per Vognsen for an implementation which both gcc and clang appear to reduce to a single asr instruction.

math: Shorten the ASR implementation

---

scripts/run-riscv

Adapt command line option code to include qemu version 10 too.

scripts: Support qemu version 10

---

newlib/libm/test/test.c

Fix testsuite for NAN bit mismatch
